import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const dest=path.resolve('.sites-runtime/ai-api-tests');fs.mkdirSync(dest,{recursive:true});
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
fs.writeFileSync(path.join(dest,'engine.mjs'),compile('lib/ai-agent.ts'));
fs.writeFileSync(path.join(dest,'route.mjs'),compile('app/api/ai/route.ts').replace(/import \{ getChatGPTUser \} from [^;]+;/,'const getChatGPTUser=async()=>globalThis.aiUser;').replace(/import \{ getDB \} from [^;]+;/,'const getDB=()=>globalThis.aiDB;').replace(/import \{ getAIConfig \} from [^;]+;/,'const getAIConfig=()=>globalThis.aiConfig;').replaceAll('@/lib/ai-agent','./engine.mjs'));
const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
globalThis.aiDB={prepare(sql){return{bind(...args){const st=sqlite.prepare(sql);return{async first(){return st.get(...args)||null;},async all(){return{results:st.all(...args)};},async run(){return{meta:{changes:Number(st.run(...args).changes)}};}};}};}};
const result={title:'Teszt',summary:'Teszt',documents:[{title:'Új szöveg',body:'Tesztválasz'}],questions:[],notes:[]};let calls=0,fail=false;
globalThis.fetch=async()=>{calls++;return fail?new Response('',{status:429}):Response.json({status:'completed',output:[{content:[{type:'output_text',text:JSON.stringify(result)}]}],usage:{total_tokens:10}});};
const {GET,POST}=await import(path.join(dest,'route.mjs'));
const get=id=>GET(new Request('https://test.example/api/ai'+(id?'?id='+id:'')));
const post=(body,origin='https://test.example')=>POST(new Request('https://test.example/api/ai',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)}));
const newWork=()=>({action:'create',id:crypto.randomUUID(),parentId:null,job:'egyedi',brief:'Írj egy új posztot.'});
globalThis.aiUser=null;globalThis.aiConfig={};assert.equal((await get()).status,401);assert.equal((await post(newWork())).status,401);
globalThis.aiUser={userId:'alpha'};assert.equal((await post(newWork(),'https://evil.example')).status,403);assert.equal((await post(newWork())).status,503);assert.equal(calls,0);assert.equal((await(await get()).json()).configured,false);
assert.equal((await post({action:'profile',content:'Céges háttér',revision:null})).status,200);assert.equal((await post({action:'profile',content:'Elavult módosítás',revision:null})).status,409);assert.equal((await post({action:'profile',content:'ú'.repeat(12000),revision:1})).status,200,'UTF-8 maximum profile');
globalThis.aiConfig={apiKey:'test-only-key'};const first=newWork();assert.equal((await post(first)).status,201);assert.equal(calls,2);assert.equal((await post(first)).status,200);assert.equal(calls,2,'immutable replay does not bill twice');assert.equal((await post({...first,brief:'Más feladat'})).status,409);
const continuation={...newWork(),parentId:first.id,brief:'Legyen rövidebb.'};assert.equal((await post(continuation)).status,201);const stored=sqlite.prepare('SELECT * FROM ai_works WHERE id=?').get(continuation.id);assert.equal(JSON.parse(stored.history_json).length,1);assert.equal(JSON.parse(stored.history_json)[0].brief,first.brief);assert.equal(stored.profile,'ú'.repeat(12000));
globalThis.aiUser={userId:'beta'};assert.equal((await get(first.id)).status,404);assert.equal((await post({...newWork(),parentId:first.id})).status,404);assert.equal((await(await get()).json()).profile,'');assert.equal((await(await get()).json()).works.length,0);
globalThis.aiUser={userId:'alpha'};const pending={...stored,id:crypto.randomUUID(),status:'pending',created_at:new Date().toISOString(),updated_at:new Date().toISOString()};const columns=Object.keys(pending);sqlite.prepare('INSERT INTO ai_works ('+columns.join(',')+') VALUES ('+columns.map(()=>'?').join(',')+')').run(...Object.values(pending));assert.equal((await post(newWork())).status,429,'concurrency admission');sqlite.prepare("UPDATE ai_works SET status='failed' WHERE id=?").run(pending.id);
fail=true;const failed=newWork();assert.equal((await post(failed)).status,429);const afterFailure=calls;assert.equal((await post(failed)).status,200);assert.equal(calls,afterFailure);assert.equal((await(await get(failed.id)).json()).work.status,'failed');fail=false;
for(let i=4;i<20;i++)assert.equal((await post(newWork())).status,201);assert.equal((await post(newWork())).status,429);assert.equal((await post(first)).status,200,'replay at quota');
globalThis.aiUser={userId:'gamma'};const template=sqlite.prepare('SELECT * FROM ai_works LIMIT 1').get();for(let i=20;i<200;i++){const row={...template,id:crypto.randomUUID(),user_id:'bulk-'+i};sqlite.prepare('INSERT INTO ai_works ('+columns.join(',')+') VALUES ('+columns.map(()=>'?').join(',')+')').run(...columns.map(c=>row[c]));}assert.equal((await post(newWork())).status,429,'site-wide quota');
console.log('PASS: actual AI route with SQLite migrations; auth/origin, UTF-8 profile, revision conflicts, per-user work/context isolation, idempotency, failures, concurrency and user/site quotas. Model responses mocked.');
