import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const dest=path.resolve('.sites-runtime/ai-tests');fs.mkdirSync(dest,{recursive:true});
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
fs.writeFileSync(path.join(dest,'engine.mjs'),compile('lib/ai-agent.ts'));
const {createAIWork,validateAIInput,validateAIResult,workMarkdown}=await import(path.join(dest,'engine.mjs'));
const draft={title:'Teszttervezet',summary:'Tesztösszefoglaló',documents:[{title:'Poszt',body:'Kizárólag tesztben használt modellválasz.'}],questions:[],notes:[]};
const envelope=result=>Response.json({status:'completed',output:[{type:'reasoning',summary:[]},{type:'message',content:[{type:'output_text',text:JSON.stringify(result)}]}],usage:{total_tokens:17}});
const input={job:'egyedi',brief:'Írj egy új posztot.',profile:'Tesztcég – nincs megadott ár.',history:[]};
let calls=[];const provider=async(url,init)=>{calls.push({url,body:JSON.parse(init.body),headers:init.headers});return envelope({...draft,title:calls.length===1?'Első':'Átnézett'});};
await assert.rejects(()=>createAIWork(input,{},provider),e=>e.code==='NOT_CONFIGURED');assert.equal(calls.length,0);
const made=await createAIWork(input,{apiKey:'test-only-key'},provider);assert.equal(made.calls,2);assert.equal(made.result.title,'Átnézett');assert.equal(made.tokens,34);assert.equal(calls[0].url,'https://api.openai.com/v1/responses');assert.equal(calls[0].body.store,false);assert.equal(calls[0].body.text.format.strict,true);assert.equal(calls[0].body.max_output_tokens,8000);assert.equal(calls[0].body.input[0].role,'developer');assert.equal(JSON.parse(calls[1].body.input[1].content).ellenorizendo_tervezet.title,'Első');assert.equal(JSON.parse(calls[1].body.input[1].content).ceges_hatter,input.profile);
const history=[{brief:input.brief,result:made.result}];calls=[];await createAIWork({...input,brief:'Rövidítsd le.',history},{apiKey:'test-only-key'},provider);assert.deepEqual(JSON.parse(calls[0].body.input[1].content).elozmenyek,history);
let clarifications=0;const ask=await createAIWork(input,{apiKey:'test-only-key'},async()=>{clarifications++;return envelope({...draft,documents:[],questions:['Melyik ajánlatot mutassam be?']});});assert.equal(clarifications,1);assert.equal(ask.calls,1);assert.equal(ask.result.documents.length,0);
for(const [response,code] of [[new Response('',{status:401}),'CREDENTIALS'],[new Response('',{status:429}),'PROVIDER_LIMIT'],[Response.json({status:'incomplete'}),'INCOMPLETE'],[Response.json({status:'completed',output:[{content:[{type:'refusal',refusal:'test'}]}]}),'REFUSAL'],[Response.json({status:'completed',output:[]}),'INVALID_OUTPUT'],[new Response('invalid'),'INVALID_OUTPUT']])await assert.rejects(()=>createAIWork(input,{apiKey:'test-only-key'},async()=>response),e=>e.code===code);
await assert.rejects(()=>createAIWork(input,{apiKey:'test-only-key'},async()=>{throw new Error('network');}),e=>e.code==='CONNECTION');
let stage=0;await assert.rejects(()=>createAIWork(input,{apiKey:'test-only-key'},async()=>++stage===1?envelope(draft):new Response('',{status:500})),e=>e.code==='PROVIDER');assert.equal(stage,2,'no silent draft fallback and no paid retry');
assert.throws(()=>validateAIInput({...input,job:'unknown'}));assert.throws(()=>validateAIInput({...input,history:Array(7).fill(history[0])}));assert.throws(()=>validateAIResult({...draft,documents:[],questions:[]}));assert.throws(()=>validateAIResult({...draft,questions:Array(4).fill('Kérdés?')}));assert.match(workMarkdown(draft),/^# Teszttervezet/);
console.log('PASS: actual shared engine, two model stages, clarification branch, grounded context, revisions, output validation, missing connection, provider errors, refusal and no automatic retries. Provider responses mocked; no live AI quality test.');
