import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
import {DatabaseSync} from 'node:sqlite';
const root=path.resolve('.sites-runtime/pilot-tests');fs.mkdirSync(root,{recursive:true});
for(const name of ['ai-agent','pilot-plan','pilot-engine','pilot-service']){let code=ts.transpileModule(fs.readFileSync('lib/'+name+'.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;for(const dep of ['ai-agent','pilot-plan','pilot-engine'])code=code.replaceAll("'./"+dep+"'","'./"+dep+".mjs'");fs.writeFileSync(root+'/'+name+'.mjs',code);}
const {PilotService}=await import(root+'/pilot-service.mjs'),{validatePilotPlan,builderToPilot}=await import(root+'/pilot-plan.mjs');
const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
function statement(sql,args=[]){return{bind(...v){return statement(sql,v);},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return{results:sqlite.prepare(sql).all(...args)};},async run(){return{meta:{changes:Number(sqlite.prepare(sql).run(...args).changes)}};}};}
const db={prepare:statement,async batch(items){sqlite.exec('BEGIN');try{const out=[];for(const q of items)out.push(await q.run());sqlite.exec('COMMIT');return out;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
class Bucket{files=new Map();corrupt=false;async put(key,value){this.files.set(key,new Uint8Array(value));}async get(key){const bytes=this.files.get(key);if(!bytes)return null;const copy=this.corrupt?new Uint8Array([0]):bytes.slice();return{body:copy,arrayBuffer:async()=>copy.buffer};}async delete(key){this.files.delete(key);}async list({prefix}){return{objects:[...this.files.keys()].filter(k=>k.startsWith(prefix)).map(key=>({key})),truncated:false};}}
const bucket=new Bucket(),config={apiKey:'test-provider-only'},result={title:'Tesztelt eredmény',summary:'Tesztben kapott válasz.',documents:[{title:'Anyag',body:'Ez kizárólag a technikai próba szolgáltatói mintaválasza.'}],questions:[],notes:[]};
const envelope=()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(result)}]}],usage:{input_tokens:20,output_tokens:30,total_tokens:50}});
let calls=0,imageCalls=0,failImage=false,gate=null,gateEnter=null;
const provider=async(url,init)=>{calls++;if(gate){gateEnter?.();await gate;}const body=JSON.parse(init.body);if(url.endsWith('/images/generations')){imageCalls++;return failImage?new Response('',{status:500}):Response.json({data:[{b64_json:'/9j/QUJDRA=='}],usage:{total_tokens:20}});}if(body.tools)return Response.json({status:'completed',output:[{type:'web_search_call',status:'completed'},{content:[{type:'output_text',text:'Dokumentált forrás tesztjegyzete.',annotations:[{type:'url_citation',title:'Forrás',url:'https://example.com/source'},{type:'url_citation',title:'Tiltott',url:'javascript:alert(1)'}]}]}],usage:{input_tokens:10,output_tokens:20,total_tokens:30}});return envelope();};
const svc=(owner='alpha',over={})=>new PilotService({db,bucket,config,fetcher:provider,...over},owner);
const plan=steps=>({version:1,name:'Próbasegítő',brief:'Írj rövid útmutatót kezdőknek.',steps});
const create=async(s,steps=['write'])=>s.create(crypto.randomUUID(),plan(steps));
async function advanceAll(s,r){while(r.status==='ready')r=await s.action(r.id,r.revision,'advance');return r;}
function setState(id,patch){const row=sqlite.prepare('SELECT * FROM pilot_runs WHERE id=?').get(id),state={...JSON.parse(row.state_json),...patch};sqlite.prepare('UPDATE pilot_runs SET state_json=? WHERE id=?').run(JSON.stringify(state),id);}
for(const bad of [null,{...plan(['write']),steps:['wat']},plan(['review','write']),plan(['write','image','review']),plan(['write','write']),plan(['search'])])assert.throws(()=>validatePilotPlan(bad));
assert.deepEqual(builderToPilot({title:'Író',request:'Írj valamit.',pieces:[{block:'request'},{block:'write'},{block:'review'},{block:'document'}]}).steps,['write','review']);
assert.throws(()=>builderToPilot({title:'Nem fut',request:'Küldd el.',pieces:[{block:'send'}]}));
let s=svc(),r=await create(s),same=await s.create(r.id,r.plan);assert.equal(same.id,r.id);await assert.rejects(()=>s.create(r.id,plan(['write','review'])),e=>e.code==='CONFLICT');
await assert.rejects(()=>svc('beta').read(r.id),e=>e.status===404);assert.equal((await svc('beta').list()).length,0);
await assert.rejects(()=>svc('alpha',{config:{}}).action(r.id,r.revision,'start'),e=>e.code==='NOT_CONFIGURED');
await assert.rejects(()=>svc('alpha',{bucket:null}).action(r.id,r.revision,'start'),e=>e.code==='STORAGE');assert.equal(calls,0);
r=await s.action(r.id,r.revision,'start');const before=calls;const concurrent=await Promise.allSettled([s.action(r.id,r.revision,'advance'),s.action(r.id,r.revision,'advance')]);assert.equal(concurrent.filter(x=>x.status==='fulfilled').length,1);assert.equal(calls,before+1,'one billable call under racing advance');r=await s.read(r.id);r=await advanceAll(s,r);assert.equal(r.status,'succeeded');assert(r.verifiedAt);assert.equal(r.usage[0].totalTokens,50);assert.deepEqual(r.events.filter(e=>e.status==='completed').map(e=>e.step),['write','save','verify']);assert.equal(calls,1,'only selected provider module executes');
const reopened=await s.read(r.id);assert.deepEqual(reopened.files,r.files);assert((await s.file(r.id,'anyag.md')).value);await assert.rejects(()=>svc('beta').file(r.id,'anyag.md'),e=>e.status===404);
const full=await create(s,['search','write','review','image']);let f=await s.action(full.id,full.revision,'start');f=await advanceAll(s,f);assert.equal(f.status,'waiting');assert.equal(imageCalls,0,'image cannot run before approval');assert.equal(f.research.sources.length,1);
failImage=true;f=await s.action(f.id,f.revision,'approve');f=await advanceAll(s,f);assert.equal(f.status,'failed');assert(f.result.documents.length);const outputs=f.outputs.length,beforeRetry=calls;
failImage=false;f=await s.action(f.id,f.revision,'retry');f=await advanceAll(s,f);assert.equal(f.status,'succeeded');assert.equal(calls,beforeRetry+1,'retry only failed image');assert.equal(f.outputs.length,outputs);assert.equal(f.files.length,2);assert(f.files.every(x=>x.path.includes(x.sha256)));
let c=await create(s,['write']);c=await s.action(c.id,c.revision,'start');c=await s.action(c.id,c.revision,'advance');c=await s.action(c.id,c.revision,'advance');assert.equal(c.cursor,2);setState(c.id,{attempts:10});c=await s.read(c.id);bucket.corrupt=true;c=await s.action(c.id,c.revision,'advance');assert.equal(c.status,'failed');assert.equal(c.verifiedAt,null,'corrupt readback must never be verified');bucket.corrupt=false;const beforeVerify=calls;c=await s.action(c.id,c.revision,'retry');c=await advanceAll(s,c);assert.equal(c.status,'succeeded');assert.equal(calls,beforeVerify,'storage retry after call cap uses no AI');
let cancel=await create(s,['write']);cancel=await s.action(cancel.id,cancel.revision,'start');let release;gate=new Promise(resolve=>release=resolve);const entered=new Promise(resolve=>gateEnter=resolve);const flight=s.action(cancel.id,cancel.revision,'advance');await entered;cancel=await s.read(cancel.id);cancel=await s.action(cancel.id,cancel.revision,'cancel');assert.equal(cancel.status,'cancelled');await assert.rejects(()=>s.remove(cancel.id,cancel.revision),e=>e.code==='CONFLICT');let other=await create(s);other=await s.action(other.id,other.revision,'start');await assert.rejects(()=>s.action(other.id,other.revision,'advance'),e=>e.code==='BUSY');release();await flight;gate=null;gateEnter=null;assert.equal((await s.read(cancel.id)).status,'cancelled','late provider result cannot resurrect cancelled run');
sqlite.prepare('UPDATE pilot_runs SET lease_until=? WHERE id=?').run('2000-01-01',cancel.id);cancel=await s.read(cancel.id);await s.remove(cancel.id,cancel.revision);await assert.rejects(()=>s.create(cancel.id,plan(['write'])),e=>e.code==='CONFLICT','deleted request ID cannot bill again');
const quota=svc('quota');for(let i=0;i<20;i++){const q=await create(quota);await quota.remove(q.id,q.revision);}await assert.rejects(()=>create(quota),e=>e.code==='QUOTA','deletion does not refund daily quota');
await s.remove(f.id,f.revision);assert(![...bucket.files.keys()].some(k=>k.includes(f.id)),'deletion clears all attempt objects');
const allSvc=svc('all-modules');let all=await create(allSvc,['search','write','summarize','tasks','translate','review','image']);all=await allSvc.action(all.id,all.revision,'start');const beforeAll=calls;all=await advanceAll(allSvc,all);assert.equal(all.status,'waiting');all=await allSvc.action(all.id,all.revision,'approve');all=await advanceAll(allSvc,all);assert.equal(all.status,'succeeded');assert.equal(calls,beforeAll+7);assert.equal(all.outputs.length,5);
// Actual API request parsing and owner boundary with test-only adapters.
let apiSource=ts.transpileModule(fs.readFileSync('app/api/pilot/route.ts','utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
apiSource=apiSource.replace(/import \{ env \} from [^;]+;/,'const env=globalThis.pilotEnv;').replace(/import \{ getChatGPTUser \} from [^;]+;/,'const getChatGPTUser=async()=>globalThis.pilotUser;').replace(/import \{ getDB \} from [^;]+;/,'const getDB=()=>globalThis.pilotDB;').replace(/import \{ getAIConfig \} from [^;]+;/,'const getAIConfig=()=>globalThis.pilotConfig;').replaceAll('@/lib/ai-agent','./ai-agent.mjs').replaceAll('@/lib/pilot-service','./pilot-service.mjs');fs.writeFileSync(root+'/route.mjs',apiSource);
globalThis.pilotEnv={BUCKET:bucket};globalThis.pilotDB=db;globalThis.pilotConfig={};globalThis.pilotUser=null;
const route=await import(root+'/route.mjs');const req=(action,origin='https://site.example')=>new Request('https://site.example/api/pilot',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(action)});
assert.equal((await route.GET(new Request('https://site.example/api/pilot'))).status,401);globalThis.pilotUser={userId:'api-user'};
assert.equal((await route.POST(req({action:'create',id:crypto.randomUUID(),plan:plan(['write'])},'https://evil.example'))).status,403);
assert.equal((await route.POST(req({action:'create',id:'bad',plan:plan(['write'])}))).status,400);
const apiRun=await(await route.POST(req({action:'create',id:crypto.randomUUID(),plan:plan(['write'])}))).json();assert.equal(apiRun.work.status,'draft');assert.equal((await route.POST(req({action:'start',id:apiRun.work.id,revision:apiRun.work.revision}))).status,503);
console.log('PASS: real SQLite migrations and service/API paths; 7-module plan validation, selected execution, race protection, image approval, checkpoint retry, readback corruption, cost metadata, cancel lease, deleted-ID replay, non-refundable quota, ownership, file cleanup, auth/origin and missing-connection behavior. AI responses and R2 adapter are simulated; no live provider claim.');
