import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import ts from 'typescript';
const root=path.resolve('.sites-runtime/research-tests');fs.mkdirSync(root,{recursive:true});
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
fs.writeFileSync(root+'/engine.mjs',compile('lib/ai-agent.ts'));
fs.writeFileSync(root+'/research.mjs',compile('lib/research-agent.ts').replaceAll('./ai-agent','./engine.mjs'));
fs.writeFileSync(root+'/workflow.mjs',compile('deploy/shared/workflow.ts').replaceAll('../../lib/ai-agent','./engine.mjs'));
const {createResearchWork,providerURL}=await import(root+'/research.mjs');
const {validateAIResult,validateAIInput}=await import(root+'/engine.mjs');
const {prepareWork,runWork,readWorkspace,userKey,key}=await import(root+'/workflow.mjs');
const result={title:'Tesztcikk',summary:'Teszt',documents:[{title:'Cikk',body:'Kész tartalom [forrás](https://example.com/source).'}],questions:[],notes:[]};
const input={job:'kutato',brief:'Fűszernövények nevelése erkélyen',profile:'Kezdőknek, barátságosan',history:[]};
const config={apiKey:'test-key',baseURL:'https://gateway.example/openai',model:'gpt-5-mini'};
const textEnvelope=r=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify(r)}]}]});
const searchEnvelope=()=>Response.json({status:'completed',output:[{type:'web_search_call',status:'completed'},{type:'message',content:[{type:'output_text',text:'Forrásból származó tesztjegyzet.',annotations:[{type:'url_citation',url:'https://example.com/source',title:'Tesztforrás'},{type:'url_citation',url:'javascript:alert(1)',title:'Rejected'}]}]}]});
let calls=[],events=[];
const provider=async(url,init)=>{const body=JSON.parse(init.body);calls.push({url,body});if(body.tools)return searchEnvelope();if(url.endsWith('images/generations'))return Response.json({data:[{b64_json:'/9j/QUJDRA=='}]});return textEnvelope(result);};
await assert.rejects(()=>createResearchWork(input,{},provider),e=>e.code==='NOT_CONFIGURED');assert.equal(calls.length,0);
const made=await createResearchWork(input,config,provider,async p=>events.push(structuredClone(p)));
assert.equal(calls.length,4);assert.equal(calls[0].url,'https://gateway.example/openai/v1/responses');assert.equal(calls[0].body.tool_choice,'required');assert.equal(calls[3].body.output_format,'jpeg');
assert.deepEqual(events.map(e=>[e.steps.at(-1).id,e.steps.at(-1).status]),['research','write','review','image'].flatMap(id=>[[id,'running'],[id,'completed']]));
assert.equal(made.result.research.sources.length,1);assert.equal(made.result.image.mime,'image/jpeg');assert.equal(validateAIResult(made.result).research.sources[0].url,'https://example.com/source');
assert(!events[0].partial);assert(events.find(e=>e.steps.at(-1).id==='write'&&e.steps.at(-1).status==='completed').partial.documents.length);
const follow=validateAIInput({...input,brief:'Legyen rövidebb.',history:[{brief:input.brief,result:made.result}]});assert(!follow.history[0].result.image,'binary image must not enter text history');
calls=[];await createResearchWork(follow,config,provider);assert.equal(JSON.parse(calls[0].body.input[1].content).eredeti_tema,input.brief);
let count=0;await assert.rejects(()=>createResearchWork(input,config,async()=>{count++;return textEnvelope(result);}),e=>e.code==='SEARCH');assert.equal(count,1,'no fake research or paid retry');
count=0;const clarified=await createResearchWork(input,config,async()=>++count===1?searchEnvelope():textEnvelope({...result,documents:[],questions:['Melyik témára gondolsz?']}));assert.equal(count,2);assert.equal(clarified.result.documents.length,0,'clarification prevents review and image');
events=[];count=0;await assert.rejects(()=>createResearchWork(input,config,async(url,init)=>{count++;if(count===4)return new Response('',{status:500});return provider(url,init);},async p=>events.push(structuredClone(p))),e=>e.code==='PROVIDER');assert.equal(count,4);assert.equal(events.at(-1).steps.at(-1).status,'failed');assert(events.at(-1).partial.documents.length,'image failure preserves reviewed text');
assert.throws(()=>validateAIResult({...result,image:{mime:'image/jpeg',data:'not-an-image'}}));assert.throws(()=>validateAIResult({...result,research:{text:'x',sources:[{url:'javascript:alert(1)',title:'bad'}]}}));
assert.equal(providerURL('https://api.openai.com/v1/','responses'),'https://api.openai.com/v1/responses');assert.throws(()=>providerURL('http://example.com','responses'));
class Store{data=new Map();v=0;async get(k){return structuredClone(this.data.get(k)?.data??null);}async getWithMetadata(k){return structuredClone(this.data.get(k)??null);}async setJSON(k,d,o={}){const p=this.data.get(k);if(o.onlyIfNew&&p||o.onlyIfMatch&&o.onlyIfMatch!==p?.etag)return{modified:false};const etag=String(++this.v);this.data.set(k,{data:structuredClone(d),etag,metadata:{}});return{modified:true,etag};}}
const store=new Store(),owner=userKey('research-test'),raw={id:crypto.randomUUID(),parentId:null,job:'kutato',brief:input.brief};await prepareWork(store,owner,raw);
let starts=0;const gen=async(i,report)=>{starts++;return(await createResearchWork(i,config,provider,p=>report(p.steps,p.partial))).result;};await Promise.all([runWork(store,owner,raw.id,gen),runWork(store,owner,raw.id,gen)]);
assert.equal(starts,1);const stored=await store.get(key(owner,raw.id));assert.equal(stored.status,'succeeded','progress CAS must not invalidate final save');assert.equal(stored.steps.length,4);assert(stored.result.image);assert(!(await readWorkspace(store,owner)).works[0].result.image,'history listing must not copy all images');
const failed={...raw,id:crypto.randomUUID()};await prepareWork(store,owner,failed);await runWork(store,owner,failed.id,async(i,report)=>{await report([{id:'image',status:'failed',at:new Date().toISOString()}],result);throw Error('image failed');});const partial=await store.get(key(owner,failed.id));assert.equal(partial.status,'failed');assert.equal(partial.result.documents.length,1);
console.log('PASS: research evidence, source safety, four real provider stages, truthful persisted progress, clarification, original-topic revision, retained partial outputs, bounded metadata, CAS completion and single worker claim. Provider calls mocked; live access still needs verification.');
