import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import ts from 'typescript';
const dest=path.resolve('.sites-runtime/tool-api-tests');fs.mkdirSync(dest,{recursive:true});
const compile=p=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext}}).outputText;
fs.writeFileSync(path.join(dest,'engine.mjs'),compile('lib/daily-tools.ts'));
fs.writeFileSync(path.join(dest,'route.mjs'),compile('app/api/tools/route.ts').replace(/import \{ getChatGPTUser \} from [^;]+;/,'const getChatGPTUser=async()=>globalThis.toolUser;').replace(/import \{ getDB \} from [^;]+;/,'const getDB=()=>globalThis.toolDB;').replaceAll('@/lib/daily-tools','./engine.mjs'));
const sqlite=new DatabaseSync(':memory:');for(const f of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(fs.readFileSync('drizzle/'+f,'utf8'));
globalThis.toolDB={prepare(sql){return{bind(...args){const st=sqlite.prepare(sql);return{async first(){return st.get(...args)||null;},async all(){return{results:st.all(...args)};},async run(){return{meta:{changes:Number(st.run(...args).changes)}};}};}};}};
const {GET,POST,DELETE}=await import(path.join(dest,'route.mjs'));
const post=(data,origin='https://test.example')=>POST(new Request('https://test.example/api/tools',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(data)}));
const del=id=>DELETE(new Request('https://test.example/api/tools?id='+id,{method:'DELETE',headers:{Origin:'https://test.example'}}));
const input={items:'Termék;Jelenlegi;Minimum;Célkészlet;Csomagméret\nPapír;2;5;12;5'};
const data={id:crypto.randomUUID(),toolId:'keszletfigyelo',kind:'result',title:'Saját készlet',input,editedText:'Saját megjegyzés'};
globalThis.toolUser=null;assert.equal((await GET()).status,401);assert.equal((await post(data)).status,401);assert.equal((await del(data.id)).status,401);
globalThis.toolUser={userId:'alpha'};assert.equal((await post(data,'https://bad.example')).status,403);assert.equal((await post({...data,input:{items:'bad'}})).status,400);assert.equal((await post({...data,toolId:'unknown'})).status,400);assert.equal((await post(data)).status,201);assert.equal((await post(data)).status,200);
let saved=(await (await GET()).json()).saves;assert.equal(saved.length,1);assert.equal(saved[0].result.text,'Saját megjegyzés');assert.equal(saved[0].result.rows[0][5],'2');
globalThis.toolUser={userId:'beta'};assert.equal((await (await GET()).json()).saves.length,0);assert.equal((await del(data.id)).status,404);assert.equal((await post(data)).status,409);
globalThis.toolUser={userId:'alpha'};assert.equal((await del(data.id)).status,200);assert.equal((await (await GET()).json()).saves.length,0);
const preset={...data,id:crypto.randomUUID(),kind:'preset'};assert.equal((await post(preset)).status,201);assert.equal((await (await GET()).json()).saves[0].result,null);
for(let i=1;i<100;i++)assert.equal((await post({...preset,id:crypto.randomUUID()})).status,201);
assert.equal((await post({...preset,id:crypto.randomUUID()})).status,409);assert.equal((await (await GET()).json()).saves.length,100);assert.equal((await post(preset)).status,200,'idempotent retry at limit');
console.log('PASS: real save/list/delete handlers with SQLite, auth and origin gates, input validation, server-computed table, edited text, immutable idempotency, user isolation, own deletion and 100-save bound.');
