import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {getUser,getSettings,handleAuthCallback,onAuthChange,login,logout,signup,requestPasswordRecovery,updateUser,acceptInvite,type User,type Settings} from '@netlify/identity';
import AIStudio from '../../app/ai-studio';
import ModuleBuilder from '../../app/module-builder';
import {Pawn} from '../../components/pawn';
import '../../kit/ai/local.css';
import '../../app/ai.css';
import './web.css';
import '../../app/brand.css';
import '../../app/module-builder.css';
function App(){
 const [user,setUser]=useState<User|null>(null),[settings,setSettings]=useState<Settings|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[library,setLibrary]=useState(false);
 const [authOpen,setAuthOpen]=useState(location.hash==='#belepes');
 useEffect(()=>{const open=()=>{if(location.hash==='#belepes')setAuthOpen(true);};window.addEventListener('hashchange',open);return()=>window.removeEventListener('hashchange',open);},[]);
 const [mode,setMode]=useState<'login'|'signup'|'recover'|'password'>('login'),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[invite,setInvite]=useState('');
 useEffect(()=>{let mounted=true;const unsub=onAuthChange((_event,current)=>{if(mounted)setUser(current);});void(async()=>{try{const callback=await handleAuthCallback();if(!mounted)return;if(callback?.type==='recovery'){setMode('password');setNotice('Adj meg új jelszót.');}else if(callback?.type==='invite'){setInvite(callback.token||'');setMode('password');}setUser(await getUser());try{setSettings(await getSettings());}catch{setError('A webes belépés beüzemelése még folyamatban van. Az útmutató és a letölthető csomag addig is használható.');}}catch{setError('A belépési hivatkozás nem használható. Kérj új jelszó-visszaállító levelet, vagy próbálj belépni.');}finally{if(mounted)setLoading(false);}})();return()=>{mounted=false;unsub();};},[]);
 async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setNotice('');try{if(mode==='recover'){await requestPasswordRecovery(email);setNotice('Ha a címhez tartozik fiók, megérkezik a visszaállításhoz szükséges levél.');}else if(mode==='password'){setUser(invite?await acceptInvite(invite,password):await updateUser({password}));setInvite('');setMode('login');setNotice('A jelszót elmentettük.');}else if(mode==='signup'){const current=await signup(email,password);if(current.confirmedAt){setUser(current);setNotice('A fiókod elkészült.');}else setNotice('Nézd meg az emailedet, és erősítsd meg a regisztrációt.');}else{setUser(await login(email,password));setNotice('Beléptél a saját munkateredbe.');}setPassword('');}catch{setError(mode==='login'?'Nem sikerült belépni. Ellenőrizd az emailt és a jelszót.':'Nem sikerült a művelet. Ellenőrizd a megadott adatokat, vagy próbáld később.');}finally{setBusy(false);}}
 return <><header className="public-header"><a href="/" className="public-brand"><Pawn size={36}/><span>Agent <span className="brand-gold">Akadémia</span></span></a><nav aria-label="Főmenü"><a href="/">Építőműhely</a><button onClick={()=>setLibrary(false)} aria-current={!library?'page':undefined}>Az első agented</button><button onClick={()=>setLibrary(true)} aria-current={library?'page':undefined}>Mentett munkák</button><a href="/letoltes/ai-kezdes.html">Útmutató</a></nav></header><main className="local-main"><section id="belepes" className="public-account">{loading?<p role="status">A munkatér megnyitása…</p>:user&&mode!=='password'?<div className="account-row"><p><strong>Saját munkatér</strong><span>{user.email}</span></p><button onClick={()=>void logout().then(()=>{setUser(null);setLibrary(false);}).catch(()=>setError('A kilépés nem sikerült. Próbáld újra.'))}>Kilépek</button></div>:<details open={authOpen||mode==='password'} onToggle={event=>setAuthOpen(event.currentTarget.open)}><summary>Belépés a saját munkatérbe</summary>{settings&&<><h2>{mode==='login'?'Folytasd ott, ahol abbahagytad.':mode==='signup'?'Legyen saját munkatársad.':mode==='recover'?'Állítsd vissza a jelszavad.':'Adj meg új jelszót.'}</h2><form onSubmit={e=>void submit(e)}>{mode!=='password'&&<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required autoComplete="email" disabled={busy}/></label>}{mode!=='recover'&&<label>Jelszó<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={mode==='login'?1:10} autoComplete={mode==='login'?'current-password':'new-password'} disabled={busy}/></label>}<button disabled={busy}>{busy?'Egy pillanat…':mode==='login'?'Belépek':mode==='signup'?'Regisztrálok':mode==='recover'?'Visszaállító levelet kérek':'Mentem a jelszót'}</button></form><div className="auth-links">{mode!=='login'&&<button onClick={()=>setMode('login')}>Már van fiókom</button>}{mode==='login'&&!settings.disableSignup&&<button onClick={()=>setMode('signup')}>Még nincs fiókom</button>}{mode==='login'&&<button onClick={()=>setMode('recover')}>Elfelejtettem a jelszavam</button>}</div><p className="local-note">A webes fiók külön tartja a hátteredet és a munkáidat. A saját gépes csomag fiók nélkül telepíthető.</p></>}</details>}{error&&<p className="simple-error" role="alert">{error}</p>}{notice&&<p className="ai-notice" role="status">{notice}</p>}</section><AIStudio key={user?.id||'guest'} user={!!user} library={library} signInHref="#belepes"/><footer className="public-footer"><a href="/letoltes/ai-kezdes.html">Első lépések</a><a href="/letoltes/agent-akademia-ai.zip" download>Saját gépes AI-csomag</a><details><summary>Korábbi eszközök</summary><p><a href="/letoltes/agent-akademia-offline.html">Számoló és rendező műhely</a></p><p><a href="/letoltes/agent-akademia-csomag.zip" download>Offline eszközcsomag</a></p></details></footer></main></>;
}
const hasAuthCallback=/access_token=|confirmation_token=|recovery_token=|invite_token=|belepes/.test(location.hash);
createRoot(document.getElementById('root')!).render(location.pathname.startsWith('/alkotas')||hasAuthCallback?<App/>:<ModuleBuilder/>);
