'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowRight, BookOpen, Check, Copy, Download, Loader2, RotateCcw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Label } from '@/components/ui/label';
import { Pawn } from '@/components/pawn';
import { aiJobs, workMarkdown, type AIJob, type AIResult } from '@/lib/ai-agent';

type Work={id:string;parentId:string|null;job:AIJob;brief:string;status:string;result:AIResult|null;error:string|null;createdAt:string};
type State={configured:boolean;profile:string;revision:number|null;works:Work[]};
function download(name:string,text:string){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function AILessons(){return <section className="ai-lessons"><div className="eyebrow">TANULJ AZ ELSŐ FELADATOD KÖZBEN</div><h2>Nem kell értened a technikához.</h2><div className="ai-lesson-grid"><article><span>01</span><h3>Adj neki célt.</h3><p>„Írj három posztot a tanfolyamomhoz.” A kész szöveget az agent alkotja meg. A tanfolyam valódi részleteit tőled ismeri meg.</p></article><article><span>02</span><h3>Nézd meg, mit alkotott.</h3><p>Olvasd át a kész anyagot. Ellenőrizd a neveket, árakat és ígéreteket. Kérhetsz változtatást: „Legyen rövidebb és közvetlenebb.”</p></article><article><span>03</span><h3>Vidd magaddal.</h3><p>A saját gépes csomag ugyanilyen feladatokat végez. Megőrzi a hátteret és a munkáidat, az eredményeket saját mappába menti.</p></article></div><details><summary>Mitől munkatárs, és mikor dolgozik?</summary><p>A Tartalomkészítő ismeri a mentett hátteret, új anyagot alkot, külön AI-lépésben átnézi a tervezetét, és folytatja a korábbi munkát. A te kérésedre indul. Önálló időzítést és publikálást ez az első változat nem végez.</p></details></section>;}

export default function AIStudio({user,library=false,local=false,signInHref='/signin-with-chatgpt?return_to=%2F'}:{user:boolean;library?:boolean;local?:boolean;signInHref?:string}){
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(user),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [profile,setProfile]=useState(''),[job,setJob]=useState<AIJob>('egyedi'),[brief,setBrief]=useState(''),[revision,setRevision]=useState(''),[work,setWork]=useState<Work|null>(null);
 const working=useRef(false),pending=useRef<{id:string;parentId:string|null;job:AIJob;brief:string}|null>(null),output=useRef<HTMLDivElement>(null);
 async function load(){setLoading(true);setError('');try{const r=await fetch('/api/ai',{cache:'no-store'}),s=await r.json() as State & {error?:string;work:Work};if(!r.ok)throw new Error(s.error);setState(s);setProfile(s.profile);}catch(e){setError(e instanceof Error?e.message:'A munkatér nem tölthető be.');}finally{setLoading(false);}}
 useEffect(()=>{if(user)void load();},[user]);
 useEffect(()=>{if(work?.status!=='pending')return;let cancelled=false;const id=work.id;const timer=setInterval(async()=>{try{const r=await fetch('/api/ai?id='+id,{cache:'no-store'});if(!r.ok)return;const s=await r.json() as {work:Work};if(cancelled)return;accept(s.work);if(s.work.status==='succeeded'){pending.current=null;setRevision('');setNotice('Elkészült, és elmentettem.');}else if(s.work.status==='failed')pending.current=null;}catch{/* The manual refresh remains available. */}},4000);return()=>{cancelled=true;clearInterval(timer);};},[work?.id,work?.status]);
 async function saveProfile(){if(!state||working.current)return;working.current=true;setBusy(true);setError('');try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',content:profile,revision:state.revision})}),s=await r.json() as State & {error?:string;work:Work};if(!r.ok)throw new Error(s.error);setState({...state,profile:s.profile,revision:s.revision});setProfile(s.profile);setNotice('Megjegyeztem. A következő feladatnál már ebből dolgozom.');}catch(e){setError(e instanceof Error?e.message:'Nem sikerült a mentés.');}finally{working.current=false;setBusy(false);}}
 function accept(w:Work){setWork(w);setJob(w.job);setState(s=>s?{...s,works:[w,...s.works.filter(x=>x.id!==w.id)].slice(0,30)}:s);}
 async function generate(followup=false){if(working.current||!state?.configured)return;const text=(followup?revision:brief).trim();if(text.length<3){setError('Írd le néhány szóban, mit szeretnél.');return;}if(profile!==state.profile){setError('Előbb mentsd el a módosított hátteret, hogy az agent abból dolgozzon.');return;}
 working.current=true;setBusy(true);setError('');setNotice('');const request={parentId:followup?work?.id||null:null,job:followup&&work?work.job:job,brief:text};
 if(!pending.current||JSON.stringify({...pending.current,id:undefined})!==JSON.stringify({...request,id:undefined}))pending.current={id:crypto.randomUUID(),...request};
 try{const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',...pending.current})}),s=await r.json() as State & {error?:string;work:Work};if(!r.ok){pending.current=null;throw new Error(s.error);}accept(s.work);if(s.work.status==='succeeded'){pending.current=null;setRevision('');setNotice('A munka elmentve. Itt folytathatod, vagy letöltheted.');setTimeout(()=>output.current?.focus(),0);}else if(s.work.status==='failed'){pending.current=null;throw new Error(s.work.error||'A munka megszakadt.');}else setNotice('Az agent dolgozik. Az eredmény automatikusan megjelenik.');}catch(e){setError((e instanceof Error?e.message:'A kapcsolat megszakadt.')+(pending.current?' Ugyanazzal a kéréssel újrapróbálva a meglévő futás állapotát kérjük le.':''));}finally{working.current=false;setBusy(false);}}
 async function refreshWork(){if(!work)return;try{const r=await fetch('/api/ai?id='+work.id,{cache:'no-store'}),s=await r.json() as State & {error?:string;work:Work};if(!r.ok)throw new Error(s.error);accept(s.work);if(s.work.status!=='pending')pending.current=null;}catch(e){setError(e instanceof Error?e.message:'Nem sikerült frissíteni.');}}
 async function copy(text:string){try{await navigator.clipboard.writeText(text);setNotice('A szöveg a vágólapra került.');}catch{setError('A másolást a böngésző nem engedte. Jelöld ki a szöveget, vagy töltsd le.');}}
 function start(){setWork(null);setRevision('');setBrief('');setNotice('');setError('');pending.current=null;}
 const dirty=!!state&&profile!==state.profile;
 return <div className="ai-studio">
  <section className="ai-opening"><header className="ai-intro"><div className="eyebrow">AGENT AKADÉMIA · TANULD MEG, VIDD HAZA</div><h1>{library?'A munkatársad emlékszik.':'Betanítod. Utána dolgozik.'}</h1><p>{library?'Nyisd meg egy korábbi munkádat, és kérj rajta változtatást.':'Egy kész Tartalomkészítő, aki megírja, átnézi és kérésedre javítja az anyagaidat. Lépésről lépésre megtanulod használni.'}</p></header>
  {!library&&<><div className="ai-agent-card"><Pawn size={58}/><div><span className="eyebrow">A TE ELSŐ AGENTED</span><h2>Tartalomkészítő</h2><p>Poszt, hirdetés, ügyféllevél, kampány és tananyag egy rövid kérésből.</p></div><span className="ai-rank">ELSŐ LÉPÉS</span><dl className="ai-agent-facts"><div><dt>Mikor</dt><dd>Amikor feladatot adsz neki</dd></div><div><dt>Mit néz</dt><dd>A kérésedet és a mentett hátteredet</dd></div><div><dt>Mit dönt el</dt><dd>Hogyan írja meg és javítsa az anyagot</dd></div><div><dt>Mit csinál</dt><dd>Új szöveget alkot, átnézi és elmenti</dd></div></dl></div></>}</section>
  {!user?<div className="ai-panel"><h2>Legyen saját munkatársad.</h2><p>A bejelentkezés a saját hátteredet és munkáidat köti hozzád.</p><Button asChild><a href={signInHref} target="_top">Belépek a munkatérbe <ArrowRight/></a></Button></div>:loading?<p role="status">A munkatér betöltése…</p>:<>
   {error&&<div className="simple-error" role="alert">{error}{!state&&<Button variant="outline" onClick={()=>void load()}>Újrapróbálom</Button>}</div>}
   {state&&!state.configured&&<div className="ai-connection"><strong>Az AI beüzemelése még hátravan.</strong><p>{local?'Az oldal tetején találod az egyszeri csatlakoztatást. Amíg az nincs kész, a feladatodat már megfogalmazhatod.':'A webes AI-szolgáltatást a működtetőnek kell egyszer csatlakoztatnia. Az alábbi feladat előkészíthető; valódi generálás a csatlakoztatás után indul. A saját gépes csomagban külön, vezetett csatlakoztatás van.'}</p></div>}
   {state&&<>
    {(library||state.works.length>0)&&<details className="ai-history" open={library}><summary>Korábbi AI-munkák ({state.works.length})</summary>{!state.works.length?<p>Még nincs mentett AI-munkád. Az első feladatot a kezdőlapon adhatod meg.</p>:state.works.map(w=><button key={w.id} disabled={busy} onClick={()=>{accept(w);setRevision('');setError('');pending.current=null;}}><span>{w.result?.title||w.brief.slice(0,70)}</span><small>{w.status==='succeeded'?'Megnyitás →':w.status==='pending'?'Folyamatban':'Megszakadt'}</small></button>)}</details>}
    {!work&&<section className="ai-panel"><div className="ai-section-title"><h2>{library?'Új feladat':'Próbáld ki egy valódi feladattal.'}</h2><BookOpen size={20}/></div><p className="muted">Elsőre kérhetsz egy rövid leckét. Ehhez semmit nem kell előre megírnod.</p><div className="ai-form"><Label htmlFor="ai-brief">Mit bíznál rá?</Label><Textarea id="ai-brief" rows={5} maxLength={6000} value={brief} disabled={busy} placeholder="Például: Taníts meg jó feladatot adni egy agentnek. Adj egy rövid magyarázatot, példát és egy gyakorlatot." onChange={e=>{setBrief(e.target.value);pending.current=null;}}/><button className="ai-text-button" disabled={busy} onClick={()=>{setBrief(job==='egyedi'?'Taníts meg jó feladatot adni egy AI-agentnek. Adj egy rövid magyarázatot, egy hétköznapi példát és egy kétperces gyakorlatot megoldással. Kezdő vagyok.':aiJobs.find(j=>j.id===job)!.example);pending.current=null;}}>Mutass egy feladatötletet</button><details><summary>Más munkát bíznál rá?</summary><Label htmlFor="ai-job">Miben segítsen?</Label><select id="ai-job" value={job} disabled={busy} onChange={e=>{setJob(e.target.value as AIJob);pending.current=null;}}>{aiJobs.map(j=><option key={j.id} value={j.id}>{j.name}</option>)}</select></details></div>
     <details className="ai-profile"><summary>Mit tudjon rólad? <span>Nem kötelező · egyszer adod meg</span></summary><p>Ha a saját vállalkozásodnak dolgozik: mivel foglalkozol, kinek segítesz, milyen stílust kedvelsz? Kész posztot vagy levelet nem kell írnod.</p><Label htmlFor="ai-profile">A te háttered</Label><Textarea id="ai-profile" rows={5} maxLength={12000} value={profile} disabled={busy} onChange={e=>setProfile(e.target.value)} placeholder="Kezdőknek segítek AI-agenteket használni. Közvetlenül, tegezve kommunikálok. Árakat csak akkor írj, ha megadtam."/><Button variant="outline" disabled={busy||!dirty} onClick={()=>void saveProfile()}>Jegyezd meg</Button><p className="field-note">A mentett háttér a saját fiókodhoz tartozik. Generáláskor az aktuális feladattal és előzményeivel együtt az OpenAI-hoz kerül.</p></details>
     <Button className="ai-main-button" disabled={busy||!state.configured||brief.trim().length<3||dirty} onClick={()=>void generate()}>{busy?<><Loader2 className="animate-spin"/> Alkot és átnézi a tervezetet…</>:<>Bízd rá a feladatot <ArrowRight/></>}</Button><p className="ai-caption">Az agent kérdez, ha a feladathoz fontos részlet hiányzik. Az eredményt automatikusan elmenti.</p>
    </section>}
    {work&&<section className="ai-panel" ref={output} tabIndex={-1}><div className="ai-section-title"><h2>{work.result?.title||'A munkád'}</h2><Button variant="ghost" disabled={busy||work.status==='pending'} onClick={start}><RotateCcw/> Új munka</Button></div><details className="ai-brief"><summary>Ezt kérted</summary><p>{work.brief}</p></details>
      {work.status==='pending'?<div role="status"><p>A feladat feldolgozása folyamatban. Az eredmény automatikusan megjelenik.</p><Button variant="outline" onClick={()=>void refreshWork()}>Állapot frissítése</Button></div>:work.status==='failed'?<p className="simple-error">{work.error}</p>:work.result&&<>
       <p>{work.result.summary}</p>{work.result.documents.map((d,i)=><article key={i} className="ai-document"><div className="ai-section-title"><h3>{d.title}</h3><Button variant="ghost" size="sm" onClick={()=>void copy(d.body)} aria-label={d.title+' másolása'}><Copy size={16}/></Button></div><div className="ai-document-body">{d.body}</div></article>)}
       {work.result.notes.length>0&&<div className="ai-check"><strong>Erre nézz rá használat előtt</strong><ul>{work.result.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></div>}
       {work.result.questions.length>0&&<div className="ai-questions"><h3>Ezt még mondd el nekem.</h3><ol>{work.result.questions.map((q,i)=><li key={i}>{q}</li>)}</ol></div>}
       <div className="ai-revision"><Label htmlFor="ai-revision">{work.result.questions.length?'Írd ide a válaszaidat':'Min változtassak?'}</Label><Textarea id="ai-revision" maxLength={6000} rows={3} value={revision} disabled={busy} onChange={e=>{setRevision(e.target.value);pending.current=null;}} placeholder={work.result.questions.length?'Rövid válaszok is elegendők.':'Például: legyen rövidebb, és magyarázd el egy hétköznapi példán.'}/><Button disabled={busy||!state.configured||revision.trim().length<3} onClick={()=>void generate(true)}>{busy?<><Loader2 className="animate-spin"/> Dolgozik a folytatáson…</>:<>Folytasd <ArrowRight/></>}</Button></div>
       {work.result.documents.length>0&&<div className="button-row"><Button variant="outline" onClick={()=>download('agent-akademia-munka.md',workMarkdown(work.result!))}><Download/> Kész anyag letöltése</Button><Button variant="ghost" onClick={()=>void copy(workMarkdown(work.result!))}><Copy/> Minden szöveg másolása</Button></div>}
      </>}
    </section>}
   </>}
  </>}
  {!library&&<AILessons/>}
  {notice&&<p className="ai-notice" role="status"><Check size={18}/>{notice}</p>}
  {local?<section className="ai-take-home"><div><div className="eyebrow">EZ MÁR A TE AGENTED</div><h2>A munkáid a saját gépeden vannak.</h2><p>A kész anyagok a csomag <strong>munkak</strong> mappájába kerülnek. Minden változat külön fájl. Legközelebb ugyanazzal az Indítás fájllal nyisd meg az agentet, és a Korábbi AI-munkák listában folytathatod.</p><p>A helyi program interneten küldi el a feladatot, a mentett hátteret és az adott munka előzményeit az OpenAI-nak. Csak a bemásolt vagy külön betöltött szöveget használja; a géped más mappáit nem olvassa.</p></div><Pawn size={104}/></section>:<section className="ai-take-home"><div><div className="eyebrow">A KÖVETKEZŐ LÉPÉSED</div><h2>A saját gépeden is legyen agented.</h2><p>Töltsd le a Tartalomkészítőt, csomagold ki, és nyisd meg a <strong>KEZDD-ITT.html</strong> útmutatót. A csomag Windows, macOS és Linux rendszeren, Node.js 22 vagy újabb verzióval indul.</p><p>Az első beüzemelésnél AI-hozzáférést kell csatlakoztatni. Utána a megszokott böngészőben használhatod; a munkák a saját gépedre mentődnek. Ez a változat internetes OpenAI-kapcsolattal dolgozik.</p><Button asChild><a href="/letoltes/agent-akademia-ai.zip" download><Download/> Saját gépes AI-csomag</a></Button>{state?.profile&&<Button variant="outline" onClick={()=>download('ceges-hatter.txt',state.profile)}>A hátteremet is viszem</Button>}</div><Pawn size={104}/></section>}
 </div>;
}
