'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Download, FolderOpen, Play, Clock3 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { automations, automationConfig } from '@/lib/automations';
import { getTool } from '@/lib/daily-tools';
import { downloadFile } from './tool-workbench';
export default function AutomationBuilder(){
 const [id,setId]=useState(automations[0].toolId),[mode,setMode]=useState<'change'|'daily'>('change'),[time,setTime]=useState('08:00');const selected=automations.find(a=>a.toolId===id)!,tool=getTool(id),config=automationConfig(id,mode,time);
 return <><div className="page-heading"><div><div className="eyebrow">LETÖLTHETŐ · AUTOMATIKUS FÁJLFELDOLGOZÁS</div><h1>Beállítod. Figyel. Elvégzi.</h1><p>Nyolc fájlfigyelő agent a saját gépedre. Nem kell hozzá AI-kulcs vagy felhőfiók.</p></div><span className="catalog-count">8 működő szabálykészlet</span></div>
  <div className="automation-intro"><FolderOpen size={26}/><div><h2>Az új fájlból magától lesz friss eredmény.</h2><p>A kicsomagolt mappába mented a CSV-t. A futó agent figyeli a változást, ellenőrzi az adatokat, majd új eredménymappát készít. Hibánál megőrzi a korábbi eredményt és jelzi a problémát.</p></div></div>
  <div className="automation-layout"><section className="panel automation-config"><span className="mini-label">A SAJÁT SZABÁLYOD</span><h2>Melyik munkát adnád át?</h2><div className="form-field"><Label htmlFor="automation-tool">Agent</Label><Select value={id} onValueChange={setId}><SelectTrigger id="automation-tool"><SelectValue/></SelectTrigger><SelectContent>{automations.map(a=><SelectItem key={a.toolId} value={a.toolId}>{a.name}</SelectItem>)}</SelectContent></Select></div>
   <div className="form-field"><Label htmlFor="automation-trigger">Mikor dolgozzon?</Label><Select value={mode} onValueChange={v=>setMode(v as 'change'|'daily')}><SelectTrigger id="automation-trigger"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="change">Ha változik a bemeneti fájl</SelectItem><SelectItem value="daily">Naponta, megadott időpontban</SelectItem></SelectContent></Select></div>
   {mode==='daily'&&<div className="form-field"><Label htmlFor="automation-time">Helyi időpont a futtató gépen</Label><Input id="automation-time" type="time" required value={time} onChange={e=>setTime(e.target.value)}/></div>}
   <dl className="automation-contract"><div><dt>Mikor?</dt><dd>{mode==='change'?'Induláskor, fájlváltozáskor és új napon; percenként ellenőriz.':`Naponta ${time||'…'} órakor, a számítógép helyi ideje szerint.`}</dd></div><div><dt>Mit néz?</dt><dd>Az általad megadott CSV-listát.</dd></div><div><dt>Mit dönt el?</dt><dd>{selected.decision}</dd></div><div><dt>Mit csinál?</dt><dd>TXT-, CSV- és JSON-eredményt ír új mappába{id==='naptar-export'?', mellé ICS-naptárfájlt':''}.</dd></div></dl>
   <div className="button-row"><Button disabled={mode==='daily'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(time)} onClick={()=>downloadFile('sajat-agent.json',JSON.stringify(config,null,2),'application/json')}><Download/> Saját beállítás letöltése</Button><Button asChild variant="outline"><Link href={'/eszkozok/'+id}><Play/> Kipróbálom itt</Link></Button></div><p className="field-note">Ez a beállítás a teljes csomaghoz tartozik. A letöltés még nem indít folyamatot.</p>
  </section><aside className="panel automation-steps"><span className="mini-label">AZ ELSŐ AUTOMATIKUS FUTÁSIG</span><h2>Egyszer kell beállítanod.</h2><ol><li><strong>Töltsd le és csomagold ki.</strong><p>A teljes csomagban a futtató és mind a nyolc példa benne van.</p><a href="/letoltes/agent-akademia-csomag.zip" download className="text-link">Teljes agentcsomag <Download size={16}/></a></li><li><strong>Cseréld a mintát a saját listádra.</strong><p>A bemenet mappában keresd a kiválasztott agent CSV-jét. Az oszlopok sorrendjét tartsd meg.</p><p className="field-note">{tool.fields.find(f=>f.key==='items')?.hint}</p></li><li><strong>Indítsd el a futtatót.</strong><p>Node.js 22 vagy újabb szükséges. Windows alatt az Inditas.bat menüből választhatsz. Macen/Linuxon a mellékelt útmutató mutatja a parancsot.</p><a href="https://nodejs.org/en/download" target="_blank" rel="noreferrer" className="text-link">Node.js letöltése <ArrowRight size={15}/></a></li><li><strong>Nézd meg az eredmenyek mappát.</strong><p>A sikeres futások külön almappákba kerülnek, a legutóbbit a legutobbi.json mutatja. A naplóban látod a futásokat és a hibákat.</p></li></ol><div className="callout"><Clock3/><p>Az automatizmus a saját gépeden fut, amíg a folyamat nyitva van. Kikapcsolt vagy alvó gépen nem dolgozik. A weboldal nem indít háttérfolyamatot, és nem csatlakozik a Gmailhez vagy a bankodhoz.</p></div></aside></div>
  <div className="section-heading"><h2>A csomagban található agentek</h2></div><div className="automation-cards">{automations.map(a=><button key={a.toolId} className={'panel '+(id===a.toolId?'selected':'')} onClick={()=>{setId(a.toolId);window.scrollTo({top:0,behavior:'smooth'});}} aria-pressed={id===a.toolId}><FolderOpen size={21}/><h3>{a.name}</h3><p>{a.decision}</p><span className="text-link">Ezt állítom be <ArrowRight size={16}/></span></button>)}</div>
 </>;
}
