'use client';

import {useEffect,useMemo,useRef,useState,type CSSProperties,type DragEvent} from 'react';
import {ArrowDown,ArrowUp,ArrowUpRight,AudioLines,Box,Check,CheckCheck,ChevronDown,ChevronRight,Clock,Download,FileText,FolderOutput,GripVertical,Image as ImageIcon,Languages,Layers3,LayoutTemplate,ListChecks,Maximize2,MousePointer2,Pause,PenLine,Play,Plus,RotateCcw,ScanText,Search,Send,ShieldCheck,Sparkles,Table2,Trash2,Upload,Volume2,X,Hand,ChartNoAxesCombined,AlignLeft,BookOpen} from 'lucide-react';
import {Pawn} from '../components/pawn';
import {blocks,clonePieces,connection,definition,families,flatten,groupPieces,initialDraft,issues,kinds,makePieces,parseDraft,recipes,uid,type Block,type Draft,type Family,type Piece} from '../lib/module-builder';
const iconMap: Record<string,typeof Box>={spark:Sparkles,audio:AudioLines,file:FileText,clock:Clock,scan:ScanText,align:AlignLeft,table:Table2,pen:PenLine,list:ListChecks,languages:Languages,image:ImageIcon,volume:Volume2,shield:ShieldCheck,hand:Hand,chart:ChartNoAxesCombined,layout:LayoutTemplate,folder:FolderOutput,send:Send,box:Box};
function BlockIcon({block,size=22}:{block:Block;size?:number}){const Icon=iconMap[block.icon]||Box;return <Icon size={size} strokeWidth={1.65}/>;}
function Port({kind}:{kind:string}){return <span className={`mb-port mb-port-${kind}`} aria-hidden="true"/>;}
const storageKey='agent-akademia-builder-v1';

export default function ModuleBuilder(){
 const [draft,setDraft]=useState<Draft>(initialDraft),[ready,setReady]=useState(false),[saved,setSaved]=useState(false);
 const [history,setHistory]=useState<Draft[]>([]),[active,setActive]=useState('first-1'),[family,setFamily]=useState<Family|'all'>('all'),[query,setQuery]=useState('');
 const [notice,setNotice]=useState('Válassz kockát. Illeszd össze. Készíts belőle saját modult.'),[help,setHelp]=useState(false),[recipesOpen,setRecipesOpen]=useState(false);
 const [grouping,setGrouping]=useState(false),[marked,setMarked]=useState<string[]>([]),[moduleName,setModuleName]=useState('Saját alkotóműhely');
 const [dragged,setDragged]=useState<{block?:string;piece?:string;module?:string}|null>(null),[dropAt,setDropAt]=useState<number|null>(null);
 const [step,setStep]=useState(-1),[playing,setPlaying]=useState(false),[inspect,setInspect]=useState<'result'|'block'>('result');
 const importRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey);if(raw){const loaded=parseDraft(raw);setDraft(loaded);setActive(loaded.pieces[0]?.uid||'');setNotice('Folytathatod az ezen a böngészőn elmentett tervedet.');}}catch{setNotice('A korábbi helyi tervet nem sikerült megnyitni. Az alapmintával indulunk.');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(storageKey,JSON.stringify(draft));setSaved(true);}catch{setSaved(false);setNotice('A böngésző nem tudja menteni a tervet. Használd a Terv letöltése gombot.');}},[draft,ready]);
 const leaves=useMemo(()=>flatten(draft.pieces),[draft.pieces]);
 const problems=useMemo(()=>issues(draft.pieces),[draft.pieces]);
 const selected=draft.pieces.find(p=>p.uid===active), selectedBlock=selected?definition(selected):undefined;
 const runningPiece=step>=0?leaves[step]:undefined;
 const currentBlock=runningPiece?definition(runningPiece):undefined;
 const done=leaves.length>0&&step===leaves.length-1;
 useEffect(()=>{if(!playing)return;if(step>=leaves.length-1){setPlaying(false);return;}const timer=window.setTimeout(()=>setStep(s=>s+1),1100);return()=>window.clearTimeout(timer);},[playing,step,leaves.length]);
 function change(next:Draft,message:string){try{next=parseDraft(JSON.stringify(next));}catch(error){setNotice(error instanceof Error?error.message:'A terv nem menthető.');return false;}setHistory(h=>[...h.slice(-19),draft]);setDraft(next);setPlaying(false);setStep(-1);setNotice(message);setDragged(null);setDropAt(null);return true;}
 function undo(){const previous=history[history.length-1];if(!previous)return;setDraft(previous);setHistory(h=>h.slice(0,-1));setPlaying(false);setStep(-1);setGrouping(false);setNotice('Az előző módosítást visszavontuk.');}
 function add(blockId:string,index=draft.pieces.length,module=false){
  if(draft.pieces.length>=40){setNotice('Egy tervbe legfeljebb 40 kocka fér. Több kockából készíts saját modult.');return;}
  const custom=module?draft.modules.find(m=>m.id===blockId):undefined;
  if(module&&!custom)return;
  const piece:Piece=custom?{uid:uid(),block:custom.id,name:custom.name,children:clonePieces(custom.children)}:{uid:uid(),block:blockId};
  change({...draft,pieces:[...draft.pieces.slice(0,index),piece,...draft.pieces.slice(index)]},`${definition(piece).name}: beillesztve. ${connection(draft.pieces[index-1],piece).ok?'':'Nézd meg a csatlakozási jelzést.'}`);
  setActive(piece.uid);setInspect('block');
 }
 function move(index:number,direction:number){const target=index+direction;if(target<0||target>=draft.pieces.length)return;const pieces=[...draft.pieces];[pieces[index],pieces[target]]=[pieces[target],pieces[index]];change({...draft,pieces},'A kockát áthelyeztük. Az illeszkedést újra ellenőriztük.');}
 function drop(event:DragEvent,index:number){event.preventDefault();if(!dragged)return;if(dragged.piece){const old=draft.pieces.findIndex(p=>p.uid===dragged.piece);if(old<0)return;const pieces=[...draft.pieces],piece=pieces.splice(old,1)[0];pieces.splice(index>old?index-1:index,0,piece);change({...draft,pieces},'A kocka az új helyére került.');}else if(dragged.block)add(dragged.block,index);else if(dragged.module)add(dragged.module,index,true);setDragged(null);setDropAt(null);}
 function toggleGroup(){setGrouping(!grouping);setMarked(draft.pieces.filter((p,i)=>i>0||definition(p).inputs.length>0).map(p=>p.uid));setPlaying(false);}
 function saveModule(){try{if(draft.modules.length>=30)throw new Error('Legfeljebb 30 saját modult menthetsz ebbe a tervbe.');const next=groupPieces(draft,marked,moduleName);change(next,'A saját kockád elkészült. A kockatárból újra beillesztheted.');setActive(next.pieces.find(p=>p.block===next.modules.at(-1)?.id)?.uid||'');setGrouping(false);setFamily('sajat');setInspect('block');}catch(error){setNotice(error instanceof Error?error.message:'A modul nem menthető.');}}
 function loadRecipe(id:string){const recipe=recipes.find(r=>r.id===id)!;const pieces=makePieces(recipe.blocks);change({...draft,title:recipe.name,pieces},`Betöltve: ${recipe.name}. Az előző összeállítás visszavonható.`);setActive(pieces[1]?.uid||pieces[0].uid);setGrouping(false);setRecipesOpen(false);setInspect('result');}
 function preview(){if(!draft.pieces.length||problems.length)return;if(playing){setPlaying(false);return;}setInspect('result');if(done||step<0)setStep(0);setPlaying(true);setNotice('Szemléltető próba indult, előre elkészített mintával. Nem használ AI-t vagy külső szolgáltatást.');}
 function download(){const blob=new Blob([JSON.stringify(draft,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),anchor=document.createElement('a');anchor.href=url;anchor.download='agent-akademia-epitesi-terv.json';anchor.click();window.setTimeout(()=>URL.revokeObjectURL(url),5000);setNotice('Az építési tervet letöltheted. Ez konfiguráció; a futtatómotor még nincs hozzá bekötve.');}
 async function importFile(file:File|undefined){if(!file)return;try{if(file.size>500_000)throw new Error('Legfeljebb 500 kB-os tervet válassz.');const next=parseDraft(await file.text());change(next,'Az építési tervet betöltöttük.');setActive(next.pieces[0]?.uid||'');setGrouping(false);}catch(error){setNotice(error instanceof Error?error.message:'A terv nem olvasható.');}if(importRef.current)importRef.current.value='';}
 const palette=blocks.filter(b=>(family==='all'||b.family===family)&&`${b.name} ${b.description}`.toLocaleLowerCase('hu').includes(query.toLocaleLowerCase('hu')));
 const customPalette=draft.modules.filter(m=>(family==='all'||family==='sajat')&&m.name.toLocaleLowerCase('hu').includes(query.toLocaleLowerCase('hu')));
 const output=draft.pieces.length?definition(draft.pieces.at(-1)!):undefined;
 const progress=leaves.length?Math.max(0,step+1)/leaves.length*100:0;
 const dragPiece=dragged?.piece?draft.pieces.find(p=>p.uid===dragged.piece):dragged?.block?{uid:'drag-preview',block:dragged.block}:dragged?.module?(()=>{const m=draft.modules.find(m=>m.id===dragged.module);return m?{uid:'drag-preview',block:m.id,name:m.name,children:m.children}:undefined;})():undefined;
 function fitsAt(index:number){if(!dragPiece)return true;const before=draft.pieces.slice(0,index).filter(p=>p.uid!==dragPiece.uid).at(-1);const after=draft.pieces.slice(index).find(p=>p.uid!==dragPiece.uid);return connection(before,dragPiece).ok&&(!after||connection(dragPiece,after).ok);}

 return <div className="module-builder" onDragEnd={()=>{setDragged(null);setDropAt(null);}} onKeyDown={e=>{if(e.key==='Escape'){setDragged(null);setDropAt(null);setGrouping(false);setRecipesOpen(false);}}}>
  <header className="mb-header"><a className="mb-brand" href="/" aria-label="Agent Akadémia kezdőlap"><Pawn size={35}/><span>Agent <b>Akadémia</b><small>SAJÁT KÉPESSÉGEK. SAJÁT SZABÁLYOK.</small></span></a><nav aria-label="Főmenü"><a className="mb-nav-active" href="/">Építőműhely</a><a href="/alkotas">Szövegalkotó <ArrowUpRight size={13}/></a><button onClick={()=>setHelp(!help)} aria-expanded={help}><BookOpen size={15}/> Így működik</button></nav><span className="mb-lab"><span/> KÍSÉRLETI MŰHELY</span></header>
  <section className="mb-intro"><div><span className="mb-eyebrow">A KÉPESSÉGEK ÖSSZEADÓDNAK.</span><h1>Kockáról kockára. <em>A te agented.</em></h1></div><p>Egy kocka egy képesség.<br/>Amit összeépítesz, abból új kocka lehet.</p></section>
  {help&&<section className="mb-guide" aria-label="Az építés menete"><button className="mb-close" onClick={()=>setHelp(false)} aria-label="Útmutató bezárása"><X size={18}/></button><div><b>01</b><h2>Válassz egy kezdést.</h2><p>Tölts be egy mintát, vagy kezdd egy indító kockával. Saját adat most nem szükséges.</p></div><div><b>02</b><h2>Illeszd a képességeket.</h2><p>Kattints a + jelre, vagy húzd be a kockát. A csatlakozó megmutatja, milyen adat megy tovább.</p></div><div><b>03</b><h2>Építs saját kockát.</h2><p>Jelölj ki egymás melletti lépéseket, nevezd el, és használd újra a saját modulodat.</p></div><p className="mb-guide-note">Ez egy működő tervszerkesztő és szemléltető műhely. A terved menthető és letölthető. A modulok AI-futtatása, ütemezése és külső kapcsolatai még nincsenek bekötve.</p></section>}
  <main className="mb-workbench">
   <aside className="mb-palette" aria-label="Kockatár"><div className="mb-panel-heading"><div><span className="mb-eyebrow">A HOZZÁVALÓK</span><h2>Kockatár <span>{blocks.length+draft.modules.length}</span></h2></div><Layers3 size={22}/></div><label className="mb-search"><Search size={15}/><input aria-label="Kocka keresése" placeholder="Milyen képesség kell?" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button onClick={()=>setQuery('')} aria-label="Keresés törlése"><X size={14}/></button>}</label><div className="mb-family-tabs" aria-label="Kockacsoportok"><button aria-pressed={family==='all'} onClick={()=>setFamily('all')}>Mind</button>{families.map(f=><button key={f.id} aria-pressed={family===f.id} onClick={()=>setFamily(f.id)}>{f.label}{f.id==='sajat'&&<span>{draft.modules.length}</span>}</button>)}</div><div className="mb-palette-list">
    {families.filter(f=>family==='all'||f.id===family).map(f=>{const items=palette.filter(b=>b.family===f.id);if(!items.length&&!(f.id==='sajat'&&customPalette.length))return null;return <section key={f.id} className="mb-family-section"><h3><span>{f.number}</span>{f.label}</h3>{items.map(b=><button key={b.id} className={`mb-palette-block mb-family-${b.family}`} draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',b.id);e.dataTransfer.effectAllowed='copy';setDragged({block:b.id});}} onClick={()=>add(b.id)} title={`${b.description} Kattints a hozzáadáshoz.`}><span className="mb-mini-icon"><BlockIcon block={b} size={19}/></span><span><strong>{b.name}</strong><small>{b.inputs.length?b.inputs.map(k=>kinds[k]).join(' / '):'Indítás'} <span aria-hidden="true">→</span> {kinds[b.output]}</small></span><Plus size={16} className="mb-add-icon"/></button>)}{f.id==='sajat'&&customPalette.map(m=>{const b=definition({uid:m.id,block:m.id,name:m.name,children:m.children});return <button key={m.id} className="mb-palette-block mb-family-sajat" draggable onDragStart={e=>{e.dataTransfer.setData('text/plain',m.id);e.dataTransfer.effectAllowed='copy';setDragged({module:m.id});}} onClick={()=>add(m.id,draft.pieces.length,true)}><span className="mb-mini-icon"><Box size={20}/></span><span><strong>{m.name}</strong><small>{flatten(m.children).length} képesség · saját modul</small></span><Plus size={16}/></button>})}</section>})}
    {!palette.length&&!customPalette.length&&<div className="mb-palette-empty"><Box size={32}/><strong>{family==='sajat'?'Itt laknak majd a saját kockáid.':'Nincs ilyen kocka.'}</strong><p>{family==='sajat'?'Építs össze legalább két kockát, majd válaszd a Saját kockává gombot.':'Próbálj egy másik keresést.'}</p></div>}
   </div><div className="mb-palette-foot"><MousePointer2 size={14}/><span>Kattints a + jelre, vagy húzd a műhelybe.</span></div></aside>
   <section className="mb-stage" aria-label="Agent összeállítása"><div className="mb-stage-toolbar"><div className="mb-project"><span className="mb-eyebrow">AZ ÖSSZEÁLLÍTÁSOD</span><label><input aria-label="Összeállítás neve" value={draft.title} maxLength={100} onChange={e=>setDraft(d=>({...d,title:e.target.value}))}/><PenLine size={13}/></label></div><div className="mb-tools"><button onClick={undo} disabled={!history.length} aria-label="Utolsó módosítás visszavonása" title="Visszavonás"><RotateCcw size={18}/></button><button className={recipesOpen?'is-active':''} onClick={()=>setRecipesOpen(!recipesOpen)} aria-expanded={recipesOpen}><Layers3 size={16}/><span>Minták</span><ChevronDown size={13}/></button></div></div>
    {recipesOpen&&<div className="mb-recipes"><span className="mb-eyebrow">INDULJ EGY ÖTLETBŐL</span>{recipes.map(r=><button key={r.id} onClick={()=>loadRecipe(r.id)}><span><strong>{r.name}</strong><small>{r.caption}</small></span><ArrowUpRight size={19}/></button>)}<button className="mb-blank" onClick={()=>{change({...draft,title:'Az én agentem',pieces:[]},'Üres műhely. Kezdd egy indító kockával.');setRecipesOpen(false);setGrouping(false);}}>Tiszta lappal kezdek <Plus size={16}/></button></div>}
    <div className="mb-stage-meta"><span><span className={`mb-status-dot ${problems.length?'mb-dot-error':''}`}/>{!draft.pieces.length?'Várja az első kockát':problems.length?`${problems.length} illesztés javítandó`:'A kockák összeillenek'}</span><span>{draft.pieces.length} kocka <span aria-hidden="true">/</span> {leaves.length} lépés</span></div>
    {grouping&&<div className="mb-group-form"><div><Box size={18}/><strong>Rakj több képességet egy kockába.</strong></div><p>Jelölj ki egymás melletti kockákat, majd adj nevet.</p><label className="mb-sr-only" htmlFor="module-name">Saját modul neve</label><input id="module-name" value={moduleName} onChange={e=>setModuleName(e.target.value)} maxLength={60}/><div><button onClick={saveModule} disabled={marked.length<2||!moduleName.trim()}><Box size={15}/>Összecsukom · {marked.length}</button><button onClick={()=>setGrouping(false)}>Mégsem</button></div></div>}
    <div className={`mb-canvas ${dragged?'mb-dragging':''} ${grouping?'mb-grouping':''}`}>
     <div className="mb-grid-label">AGENT / 001<span>ÉPÍTÉSI NÉZET</span></div>
     <div className="mb-chain">
      {draft.pieces.map((piece,i)=>{const b=definition(piece),link=connection(draft.pieces[i-1],piece),activeLeaf=runningPiece&&(piece.children?flatten(piece.children).some(p=>p.uid===runningPiece.uid):piece.uid===runningPiece.uid);const completed=step>=0&&(piece.children?flatten(piece.children).every(p=>leaves.indexOf(p)<step):leaves.indexOf(piece)<step);const isMarked=marked.includes(piece.uid);return <div key={piece.uid} className={`mb-chain-unit ${activeLeaf?'mb-unit-running':''}`}>
       <div className={`mb-joint ${!link.ok?'mb-joint-error':''} ${dropAt===i?'mb-drop-active':''} ${dragged?(fitsAt(i)?'mb-slot-fits':'mb-slot-mismatch'):''}`} onDragOver={e=>{if(dragged){e.preventDefault();setDropAt(i);}}} onDrop={e=>drop(e,i)}>
        {i===0&&link.ok?<span className="mb-start"><span/> ITT INDUL</span>:link.ok?<><span className="mb-wire"/><span className="mb-joint-label"><Port kind={definition(draft.pieces[i-1]).output}/>{link.message}</span></>:<div className="mb-connection-error"><span>{link.message}</span>{link.suggestion&&<button onClick={()=>add(link.suggestion!,i)}><Plus size={13}/>{blocks.find(item=>item.id===link.suggestion)!.name}: tedd közé</button>}</div>}
        {dragged&&<span className="mb-drop-label">{fitsAt(i)?'Ide illik · engedd el':'Beilleszthető · az illesztést javítani kell'}</span>}
       </div>
       <div className={`mb-block-shell mb-family-${b.family} ${active===piece.uid?'mb-selected':''} ${activeLeaf?'mb-running':''} ${completed?'mb-completed':''} ${grouping&&isMarked?'mb-marked':''}`} style={{'--block-index':i} as CSSProperties}>
        <div className="mb-studs" aria-hidden="true"><i/><i/><i/></div>
        <button className="mb-block-face" draggable={!grouping} onDragStart={e=>{e.dataTransfer.setData('text/plain',piece.uid);e.dataTransfer.effectAllowed='move';setDragged({piece:piece.uid});}} onClick={()=>{if(grouping)setMarked(m=>m.includes(piece.uid)?m.filter(id=>id!==piece.uid):[...m,piece.uid]);else{setActive(piece.uid);setInspect('block');}}} aria-pressed={grouping?isMarked:active===piece.uid} aria-label={`${i+1}. ${b.name}${grouping?', kijelölés a saját modulhoz':''}`}>
         <span className="mb-block-icon"><BlockIcon block={b} size={27}/></span><span className="mb-block-copy"><small>{b.verb}</small><strong>{b.name}</strong>{piece.children&&<span className="mb-inside-tags">{piece.children.slice(0,5).map(child=><span key={child.uid}><BlockIcon block={definition(child)} size={12}/></span>)}<span>{flatten(piece.children).length} képesség</span></span>}</span><span className="mb-block-number">{grouping?<span className="mb-select-box">{isMarked&&<Check size={16}/>}</span>:completed?<Check size={20}/>:String(i+1).padStart(2,'0')}</span><GripVertical className="mb-grip" size={15}/>
        </button><div className="mb-block-edge" aria-hidden="true"><span>{kinds[b.output]}</span><i/><i/><i/></div>
        {!grouping&&active===piece.uid&&<div className="mb-block-controls"><button disabled={i===0} onClick={()=>move(i,-1)} aria-label={`${b.name} feljebb`}><ArrowUp size={14}/></button><button disabled={i===draft.pieces.length-1} onClick={()=>move(i,1)} aria-label={`${b.name} lejjebb`}><ArrowDown size={14}/></button><button onClick={()=>{change({...draft,pieces:draft.pieces.filter(p=>p.uid!==piece.uid)},`${b.name}: kivettük. Visszavonással helyreállítható.`);setActive('');}} aria-label={`${b.name} eltávolítása`}><Trash2 size={14}/></button></div>}
       </div>
      </div>})}
      <div className={`mb-chain-end ${dropAt===draft.pieces.length?'mb-drop-active':''} ${dragged?(fitsAt(draft.pieces.length)?'mb-slot-fits':'mb-slot-mismatch'):''}`} onDragOver={e=>{if(dragged){e.preventDefault();setDropAt(draft.pieces.length);}}} onDrop={e=>drop(e,draft.pieces.length)}>{draft.pieces.length?<><span className="mb-wire"/><span className="mb-end-cap"><CheckCheck size={14}/>{kinds[output!.output]} a végén</span>{dragged&&<span className="mb-drop-label">{fitsAt(draft.pieces.length)?'Ide illik · az összeállítás végére':'Beilleszthető · az illesztést javítani kell'}</span>}</>:<div className="mb-empty-stage"><div className="mb-empty-cube"><Plus size={36}/></div><h2>Az első kocka a kezdet.</h2><p>Válassz a Kockatárból egy indító képességet,<br/>vagy kezdj egy kész mintával.</p><button onClick={()=>add('request')}><Sparkles size={16}/> Kéréssel indítok</button></div>}</div>
     </div><div className="mb-canvas-caption"><span>ÉPÍTSD. ÉRTSD. ALAKÍTSD.</span><span>AA—01</span></div>
    </div>
    <div className="mb-stage-bottom"><button className="mb-make-module" disabled={draft.pieces.length<2} onClick={toggleGroup}><Box size={18}/><span>{grouping?'Kijelölés bezárása':'Saját kockává'}</span></button><span>Összeépíted. Elnevezed. Újra használod.</span></div>
   </section>
   <aside className="mb-inspector" aria-label="Eredmény és kocka részletei"><div className="mb-inspector-tabs"><button aria-pressed={inspect==='result'} onClick={()=>setInspect('result')}>A végeredmény</button><button aria-pressed={inspect==='block'} onClick={()=>setInspect('block')}>A kocka belülről</button></div>
    {inspect==='block'&&selectedBlock&&selected?<div className="mb-inspect-body"><span className="mb-eyebrow">EGY KÉPESSÉG KÖZELRŐL</span><div className={`mb-detail-icon mb-family-${selectedBlock.family}`}><BlockIcon block={selectedBlock} size={28}/></div><h2>{selectedBlock.name}</h2><p>{selectedBlock.description}</p><div className="mb-port-detail"><div><small>EZT KAPJA</small><strong>{selectedBlock.inputs.length?selectedBlock.inputs.map(k=><span key={k}><Port kind={k}/>{kinds[k]}</span>):'Te indítod el'}</strong></div><ArrowDown size={18}/><div><small>EZT ADJA TOVÁBB</small><strong><Port kind={selectedBlock.output}/>{kinds[selectedBlock.output]}</strong></div></div>{selected.children&&<section className="mb-inside"><h3>A kocka képességei</h3>{selected.children.map((p,i)=><div key={p.uid}><span>{String(i+1).padStart(2,'0')}</span><BlockIcon block={definition(p)} size={16}/><strong>{definition(p).name}</strong></div>)}<button onClick={()=>{const index=draft.pieces.findIndex(p=>p.uid===selected.uid);change({...draft,pieces:[...draft.pieces.slice(0,index),...clonePieces(selected.children!),...draft.pieces.slice(index+1)]},'A modult szétnyitottuk. A saját kockatárban továbbra is megmarad.');setActive('');setInspect('result');}}><Maximize2 size={15}/> Szétnyitom a műhelyben</button></section>}<div className="mb-capability-note"><span>TERVEZHETŐ KÉPESSÉG</span><p>{selectedBlock.needs?`${selectedBlock.needs} szükséges a valódi működéshez.`:'A kocka AI-futtatása még nincs bekötve.'} A látványpróba előre elkészített mintát mutat.</p></div></div>:<div className="mb-inspect-body"><div className="mb-output-heading"><span className="mb-eyebrow">EZ ÁLL ÖSSZE BELŐLE</span><span className="mb-example-badge">MINTA</span></div><h2>{currentBlock?currentBlock.name:output?`${kinds[output.output]}. Készen az átadásra.`:'Mi készüljön?'}</h2><p>{currentBlock?'Ezt adná tovább ez a lépés. Az alábbi tartalom előre megírt példa.':'A kockáid meghatározzák, milyen eredményt készítene az agent.'}</p>
     <div className={`mb-result-preview ${currentBlock?'mb-result-live':''}`}><div className="mb-paper-top"><Pawn size={20}/><span>AGENT AKADÉMIA<br/>MINTAEREDMÉNY</span><span>01</span></div>{currentBlock?<div className="mb-sample-content"><span className="mb-document-label">{kinds[currentBlock.output]}</span><h3>{currentBlock.name}</h3><p>{currentBlock.sample}</p>{currentBlock.output==='image'&&<div className="mb-image-placeholder"><ImageIcon size={38}/><span>A létrejövő kép helye</span></div>}</div>:<><span className="mb-document-label">{output?kinds[output.output]:'A TE ÖTLETED'}</span><h3>{draft.title||'A következő nagy ötleted.'}</h3><div className="mb-preview-lines" aria-hidden="true"><i/><i/><i/></div><div className="mb-preview-check"><span><Check size={11}/></span><div><strong>Összeáll a tartalom</strong><i/></div></div><div className="mb-preview-check"><span><Check size={11}/></span><div><strong>Helyére kerül a lényeg</strong><i/></div></div><div className="mb-preview-check"><span><Check size={11}/></span><div><strong>Készülhet a végső anyag</strong><i/></div></div></>}<div className="mb-paper-footer">ELŐRE ELKÉSZÍTETT SZEMLÉLTETÉS <span>AA</span></div></div>
     <div className="mb-result-caption"><span className="mb-status-dot"/> {done?'A minta végigért. Valódi fájl nem készült.':step>=0?`${step+1}. lépés a(z) ${leaves.length}-ból`:'A mintában még nincs saját adat.'}</div>
     <div className="mb-output-summary"><div><strong>{leaves.length}</strong><span>összekapcsolt lépés</span></div><div><strong>{draft.pieces.filter(p=>p.children).length}</strong><span>saját modul</span></div></div>
    </div>}
    <section className="mb-trial"><div className="mb-trial-heading"><span className="mb-eyebrow">NÉZD MEG AZ ADAT ÚTJÁT</span><span>{Math.round(progress)}%</span></div><div className="mb-progress"><span style={{width:`${progress}%`}}/></div><div className="mb-trial-actions"><button className="mb-play" disabled={!draft.pieces.length||problems.length>0} onClick={preview}>{playing?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{playing?'Szünet':done?'Újra lejátszom':'Látványpróba'}</button><button disabled={!leaves.length||problems.length>0||done} onClick={()=>{setPlaying(false);setStep(s=>Math.min(s+1,leaves.length-1));setInspect('result');}} aria-label="Következő mintalépés" title="Következő lépés"><ChevronRight size={20}/></button><button disabled={step<0} onClick={()=>{setPlaying(false);setStep(-1);}} aria-label="Minta visszaállítása" title="Visszaállítás"><RotateCcw size={16}/></button></div><p><strong>Nincs AI-futtatás.</strong> Előre elkészített minta halad végig a kockákon.</p>{problems.length>0&&<p className="mb-trial-error">A próbához előbb javítsd az illesztéseket.</p>}</section>
   </aside>
  </main>
  <footer className="mb-footer"><div className="mb-save-state"><span className={`mb-status-dot ${saved?'':'mb-dot-error'}`}/>{saved?'Ezen a böngészőn mentve':'Helyi mentésre vár'}<span className="mb-footer-divider"/><span>A terved a tiéd.</span></div><div><input ref={importRef} type="file" accept=".json,application/json" className="mb-sr-only" tabIndex={-1} onChange={e=>void importFile(e.target.files?.[0])}/><button onClick={()=>importRef.current?.click()}><Upload size={15}/>Terv betöltése</button><button onClick={download}><Download size={15}/>Terv letöltése</button></div></footer>
  <div className="mb-notice" role="status" aria-live="polite"><span>↳</span>{notice}</div>
 </div>;
}
