'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUp,ArrowRight,Check,Download,FolderOpen,Image as ImageIcon,Loader2,Plus,RotateCcw,Search,ShieldCheck,Sparkles,Trash2,X,FileText,BookOpen,Pause} from 'lucide-react';
import {Pawn} from '../components/pawn';
import {Button} from '../components/ui/button';
import {Textarea} from '../components/ui/textarea';
import {Input} from '../components/ui/input';
import {Label} from '../components/ui/label';
import {pilotModules,pilotRecipes,planProblem,validatePilotPlan,type PilotPlan,type PilotStep} from '../lib/pilot-plan';
import {addPilotCard,maxPilotCards,pilotCardHelp,pilotSelection} from '../lib/card-guidance';
import type {PilotRun,PilotFile} from '../lib/pilot-engine';
import './pilot-workshop.css';
type PublicFile=Omit<PilotFile,'path'>&{url:string};
type Run=Omit<PilotRun,'files'>&{files:PublicFile[]};
type BriefWork={id:string;plan:PilotPlan;status:Run['status'];createdAt:string;verifiedAt:string|null};
type Payload={error?:string;configured?:boolean;work?:Run;works?:BriefWork[]};
type Folder={name:string;getDirectoryHandle(name:string,options:{create:boolean}):Promise<Folder>;getFileHandle(name:string,options:{create:boolean}):Promise<{createWritable():Promise<{write(bytes:Uint8Array):Promise<void>;close():Promise<void>}>;getFile():Promise<File>}>};
const blank=():PilotPlan=>({version:1,name:'Az én segítőm',brief:'',steps:[]});
const stepName=(id:string)=>pilotModules.find(m=>m.id===id)?.name||({save:'Elmenti',verify:'Visszaellenőrzi',run:'Feladat',plan:'Összeállítás'}[id]||id);
const statusName=(s:string)=>({draft:'Elmentett összeállítás',ready:'Folytatható',running:'Dolgozik',waiting:'A döntésedre vár',failed:'Megállt',clarification:'Pontosítást kér',succeeded:'Elkészült, mentés ellenőrizve',cancelled:'Leállítva'}[s]||s);
function LinkedText({text}:{text:string}){return <>{text.split(/(\[[^\]\n]{1,300}\]\(https?:\/\/[^\s)]+\))/g).map((part,i)=>{const m=part.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);return m?<a key={i} href={m[2]} target="_blank" rel="noopener noreferrer">{m[1]}</a>:part;})}</>;}
export default function PilotWorkshop({user=false}:{user?:boolean}){
 const [plan,setPlan]=useState<PilotPlan>(blank),[run,setRun]=useState<Run|null>(null),[works,setWorks]=useState<BriefWork[]>([]),[configured,setConfigured]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[tab,setTab]=useState<'result'|'steps'|'sources'>('result'),[folder,setFolder]=useState<Folder|null>(null),[folderNotice,setFolderNotice]=useState(''),[deleteAsk,setDeleteAsk]=useState(false);
 const lock=useRef(false),halt=useRef(false),attempt=useRef<{key:string;id:string}|null>(null),latestRun=useRef<Run|null>(null);
 async function api(body?:unknown,id?:string):Promise<Payload>{const r=await fetch('/api/pilot'+(id?'?id='+encodeURIComponent(id):''),body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{cache:'no-store'});let p:Payload;try{p=await r.json();}catch{throw Error('Megszakadt a kapcsolat. A Korábbi munkák között ellenőrizheted a mentést.');}if(!r.ok)throw Error(p.error||'A kérés nem sikerült.');return p;}
 function accept(r:Run){const previous=latestRun.current;if(previous?.id===r.id&&previous.revision>r.revision)return;latestRun.current=r;setRun(r);setWorks(old=>[{id:r.id,plan:r.plan,status:r.status,createdAt:r.createdAt,verifiedAt:r.verifiedAt},...old.filter(x=>x.id!==r.id)]);}
 async function load(){try{const p=await api();setWorks(p.works||[]);setConfigured(!!p.configured);}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(user)void load();try{const passed=sessionStorage.getItem('aa-pilot-plan');if(passed){setPlan(validatePilotPlan(JSON.parse(passed)));sessionStorage.removeItem('aa-pilot-plan');setNotice('Az összeállításod átkerült ide. Indítás előtt még szabadon módosíthatod.');}}catch{setNotice('Az előző összeállítás nem tölthető be. Válassz egy feladatötletet.');}},[user]);
 async function open(id:string){if(lock.current)return;setError('');setFolderNotice('');try{const p=await api(undefined,id);if(p.work){accept(p.work);setPlan(p.work.plan);setConfigured(!!p.configured);setDeleteAsk(false);}}catch(e){setError((e as Error).message);}}
 useEffect(()=>{if(!run||(!busy&&run.status!=='running'))return;let live=true;const id=run.id;const timer=setInterval(()=>{void api(undefined,id).then(p=>{if(live&&p.work)accept(p.work);}).catch(()=>{});},3000);return()=>{live=false;clearInterval(timer);};},[run?.id,run?.status,busy]);
 async function drive(current:Run){let r=current;while(r.status==='ready'&&!halt.current){const p=await api({action:'advance',id:r.id,revision:r.revision});if(!p.work)throw Error('A munkabejegyzés nem érkezett meg.');r=p.work;accept(r);}return r;}
 async function operate(action:'start'|'approve'|'retry'|'continue',target=run){if(!target||lock.current)return;lock.current=true;halt.current=false;setBusy(true);setError('');try{const p=action==='continue'?{work:target}:await api({action,id:target.id,revision:target.revision});if(p.work){accept(p.work);await drive(p.work);}}catch(e){setError((e as Error).message);try{const p=await api(undefined,target.id);if(p.work)accept(p.work);}catch{}}finally{lock.current=false;setBusy(false);}}
 async function create(start:boolean){if(lock.current)return;const problem=planProblem(plan);if(problem){setError(problem);return;}lock.current=true;setBusy(true);setError('');setNotice('');setFolderNotice('');setDeleteAsk(false);const key=JSON.stringify(plan);if(attempt.current?.key!==key)attempt.current={key,id:crypto.randomUUID()};let created:Run|undefined;
  try{const p=await api({action:'create',id:attempt.current.id,plan});created=p.work;if(created){accept(created);setNotice('Az összeállítást elmentettük a saját munkateredbe.');}}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}
  if(start&&created){if(created.status==='draft')await operate('start',created);else setNotice('Ez a kérés már mentve van. A meglévő munka állapotát mutatjuk; új futáshoz használd az Új munkaként gombot.');}
 }
 async function stop(){if(!run)return;halt.current=true;try{const current=(await api(undefined,run.id)).work;if(current){const p=await api({action:'cancel',id:current.id,revision:current.revision});if(p.work)accept(p.work);setNotice('További lépést nem indítunk. A már elküldött AI-kérés még fogyaszthat.');}}catch(e){setError((e as Error).message);}}
 function edit(change:Partial<PilotPlan>){setPlan(p=>({...p,...change}));attempt.current=null;setError('');}
 function move(i:number,d:number){const steps=[...plan.steps];[steps[i],steps[i+d]]=[steps[i+d],steps[i]];edit({steps});}
 async function chooseFolder(){try{const picker=(window as unknown as {showDirectoryPicker?:()=>Promise<Folder>}).showDirectoryPicker;if(!picker){setFolderNotice('Ebben a böngészőben a Fájl letöltése gombbal menthetsz. A helyét a böngésző kérdezi meg, vagy a Letöltések mappába teszi.');return;}setFolder(await picker());setFolderNotice('A kiválasztott mappába külön jóváhagyásoddal másoljuk a kész fájlokat.');}catch(e){if((e as Error).name!=='AbortError')setFolderNotice('A mappa nem nyitható meg. Használhatod a letöltést is.');}}
 async function saveFolder(){if(!folder||!run?.verifiedAt)return;setFolderNotice('Átmásoljuk és visszaolvassuk a fájlokat…');try{const target=await folder.getDirectoryHandle('Agent-Akademia-'+run.id,{create:true});for(const f of run.files){const response=await fetch(f.url,{cache:'no-store'});if(!response.ok)throw Error('A mentett fájl nem tölthető le.');const bytes=new Uint8Array(await response.arrayBuffer());const handle=await target.getFileHandle(f.name,{create:true}),writer=await handle.createWritable();await writer.write(bytes);await writer.close();const reopened=await handle.getFile();const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',await reopened.arrayBuffer())),b=>b.toString(16).padStart(2,'0')).join('');if(hash!==f.sha256||reopened.size!==f.bytes)throw Error('A visszaolvasott fájl eltér az eredetitől.');}setFolderNotice('A böngésző visszaellenőrizte a másolatokat: '+folder.name+' / '+target.name+'. Azonos munkánál ugyanebbe az almappába mentünk.');}catch(e){setFolderNotice((e as Error).message+' A webes példány megmaradt.');}}
 async function remove(){if(!run)return;try{await api({action:'delete',id:run.id,revision:run.revision});setWorks(ws=>ws.filter(w=>w.id!==run.id));setRun(null);latestRun.current=null;attempt.current=null;setDeleteAsk(false);setNotice('A munkát és a hozzá tartozó fájlokat töröltük.');}catch(e){setError((e as Error).message);}}
 const selection=pilotSelection(plan.steps),problem=planProblem(plan),selectedChanged=run&&JSON.stringify(plan)!==JSON.stringify(run.plan),image=run?.files.find(f=>f.name==='kep.jpg'),actualSteps=run?[...run.plan.steps,'save','verify']:[],result=run?.result;
 const tokens=run?.usage.reduce((n,u)=>n+(u.totalTokens||0),0)||0,unknown=run?.usage.some(u=>!u.confirmed||u.totalTokens===null);
 return <div className="pw"><header className="pw-header"><a href="/" className="pw-brand"><Pawn size={30}/><span>Agent Akadémia</span></a><nav><a href="/epito">Korábbi terveim</a><a href="#pw-help"><BookOpen size={17}/> Útmutató</a><span>Privát próba</span></nav></header>
  <main className="pw-main"><div className="pw-heading"><div><p className="pw-eyebrow">A SAJÁT AI-SEGÍTŐD</p><h1>Rakd össze. Bízd rá. Nézd meg.</h1><p>Te mondod meg a célt. A kiválasztott lépések elkészítik az anyagot.</p></div><div className="pw-destination"><FolderOpen size={22}/><div><strong>Ide kerül az eredmény</strong><span>Saját munkatered → letölthető fájl</span></div></div></div>
   <div className="pw-ideas" aria-label="Kész feladatötletek">{pilotRecipes.map(r=><button key={r.name} disabled={busy} onClick={()=>edit({name:r.name,brief:r.brief,steps:[...r.steps]})}><Sparkles size={16}/>{r.name}<ArrowRight size={16}/></button>)}</div>
   <section className="pw-rules" aria-label="Hány kártya kell a segítőhöz?"><div><span>MINIMUM</span><strong>1 kártya</strong><p>Megírja <b>vagy</b> Teendőket készít. Ebből már lehet segítőd.</p></div><div><span>MAXIMUM</span><strong>{maxPilotCards} különböző kártya</strong><p>Mindegyik egyszer szerepelhet. Csak azt válaszd, amire szükséged van.</p></div><div><span>AMI MINDIG KELL</span><strong>Írd le a feladatot</strong><p>Az ötleted elég. A kész szöveget az AI hozza létre.</p></div></section>
   <div className="pw-build"><section className="pw-catalog"><h2>Válassz kártyákat</h2><p>A + gomb hozzáadja, és a megfelelő helyre illeszti a kártyát.</p>{pilotModules.map(m=>{const help=pilotCardHelp[m.id],chosen=plan.steps.includes(m.id);return <button key={m.id} aria-label={m.name+(chosen?' — már kiválasztva':' hozzáadása')} disabled={busy||chosen||plan.steps.length>=maxPilotCards} className={'pw-module pw-kind-'+m.kind+(chosen?' pw-chosen':'')} onClick={()=>edit({steps:addPilotCard(plan.steps,m.id)})}><span><strong>{m.name}</strong><small>{m.detail}</small><span className="pw-card-minimum">{chosen?'Kiválasztva · ':''}{help.minimum===1?'Önállóan is elég':'Minimum 2 kártyával'}</span><small className="pw-card-requirement">{help.requirement}</small></span>{chosen?<Check size={20}/>:<Plus size={20}/>}</button>;})}</section>
    <section className="pw-canvas" aria-label="A saját segítőd összeállítása"><div className="pw-canvas-top"><span className="pw-eyebrow">ITT ÁLL ÖSSZE A SEGÍTŐD</span><button disabled={busy} onClick={()=>{edit(blank());setRun(null);}}>Üres mező</button></div><Label htmlFor="pw-brief">Mit készítsen el?</Label><Textarea id="pw-brief" value={plan.brief} rows={3} maxLength={6000} disabled={busy} onChange={e=>edit({brief:e.target.value})} placeholder="Például: dolgozz ki egy kezdőknek szóló AI-workshopot, majd készíts teendőlistát."/>
     <div className="pw-card-count"><strong>{plan.steps.length} / {maxPilotCards} kártya</strong><span>{plan.steps.length===maxPilotCards?'Elérted a maximumot. A cseréhez vegyél ki egy kártyát.':'Minden kártyából legfeljebb egyet választhatsz.'}</span></div>
     <section className={'pw-readiness '+(selection.problem?'pw-needs-card':'pw-cards-ok')} aria-live="polite" aria-label="A kártyák ellenőrzése"><strong>{!plan.steps.length?'Kezdésnek válassz egy alapfeladatot.':selection.problem?'Még hiányzik valami az összeállításból.':'A kártyák összeillenek.'}</strong>{selection.missingBase?<><p>{plan.steps.length?'Ezek mellé kell egy kártya, amely elkészíti a szöveget. Válassz a kettő közül:':'Új szöveget szeretnél, vagy teendőlistát?'}</p><div><Button variant="outline" disabled={busy} onClick={()=>edit({steps:addPilotCard(plan.steps,'write')})}><Plus size={16}/> Megírja hozzáadása</Button><Button variant="outline" disabled={busy} onClick={()=>edit({steps:addPilotCard(plan.steps,'tasks')})}><Plus size={16}/> Teendőket készít hozzáadása</Button></div></>:selection.problem?<><p>{selection.problem}</p>{selection.orderWrong&&<Button variant="outline" disabled={busy} onClick={()=>edit({steps:selection.reordered})}><RotateCcw size={16}/> Sorrend javítása</Button>}</>:<p>Nem kötelező több kártya. A mentést és a visszaellenőrzést automatikusan hozzáadjuk.</p>}</section>
     {!plan.steps.length?<div className="pw-empty"><Plus size={32}/><strong>Ide kerülnek a választott kártyák.</strong><p>A fenti két gomb közül bármelyikkel elkezdheted.</p></div>:<ol className="pw-chain">{plan.steps.map((id,i)=><li key={id}><span className="pw-number">{String(i+1).padStart(2,'0')}</span><div><strong>{stepName(id)}</strong><small>{pilotModules.find(m=>m.id===id)?.detail}</small></div><div className="pw-move"><button aria-label={stepName(id)+' feljebb'} disabled={busy||i===0} onClick={()=>move(i,-1)}><ArrowUp size={16}/></button><button aria-label={stepName(id)+' lejjebb'} disabled={busy||i===plan.steps.length-1} onClick={()=>move(i,1)}><ArrowDown size={16}/></button><button aria-label={stepName(id)+' eltávolítása'} disabled={busy} onClick={()=>edit({steps:plan.steps.filter(s=>s!==id)})}><X size={18}/></button></div></li>)}</ol>}
     <div className="pw-fixed"><FolderOpen size={18}/><span>Automatikus mentés</span><ArrowRight size={16}/><ShieldCheck size={18}/><span>Visszaellenőrzés</span></div>
     <details className="pw-name"><summary>Adj nevet a segítődnek</summary><Label htmlFor="pw-name">Név</Label><Input id="pw-name" value={plan.name} maxLength={100} onChange={e=>edit({name:e.target.value})}/></details>
     {plan.steps.length>0&&!selection.problem&&problem&&<p className="pw-hint">{!plan.name.trim()?'Adj nevet a segítődnek a fenti mezőben.':problem}</p>}
     {user&&plan.steps.length>0&&!problem&&configured===false&&<p className="pw-hint">Az összeállítás kész és menthető. A Kipróbálom gomb az AI-kapcsolat beállítása után működik.</p>}
     <div className="pw-actions">{user?<><Button disabled={busy||!!problem||configured!==true} onClick={()=>void create(true)}>{busy?<Loader2 className="pw-spin" size={18}/>:<Sparkles size={18}/>} Kipróbálom</Button><Button variant="outline" disabled={busy||!!problem} onClick={()=>void create(false)}>Összeállítás mentése</Button></>:<Button asChild><a href="/signin-with-chatgpt?return_to=%2Fproba" target="_top">Belépek a saját próbámhoz <ArrowRight size={18}/></a></Button>}</div>
     <p className="pw-small">{plan.steps.length?plan.steps.length+' választott lépés. ':''}Minden AI-lépés szolgáltatói használatot jelent. Képkészítés előtt külön megáll és megkérdez.</p>
    </section></div>
   {configured===false&&<aside className="pw-connection"><strong>Az összeállítás menthető. A valódi AI-indításhoz még egy csatlakoztatás szükséges.</strong><p>Az AI-hozzáférés vagy a mentési tárhely még nincs csatlakoztatva. Az indítás ezek beállítása után lesz elérhető.</p><button onClick={()=>void load()}>Kapcsolat újraellenőrzése</button></aside>}
   {error&&<p className="pw-error" role="alert">{error}</p>}{notice&&<p className="pw-notice" role="status">{notice}</p>}
   <section className="pw-work"><aside className="pw-history"><h2>Korábbi munkák</h2>{!works.length?<p>A mentett összeállításaid és eredményeid itt maradnak.</p>:works.map(w=><button className={w.id===run?.id?'pw-active':''} key={w.id} disabled={busy} onClick={()=>void open(w.id)}><strong>{w.plan.name}</strong><span>{statusName(w.status)}</span></button>)}</aside>
    <section className="pw-output" aria-live="polite"><div className="pw-output-top"><div><span className="pw-eyebrow">EREDMÉNY ÉS VISSZAJELZÉS</span><h2>{run?(busy&&run.status==='ready'?'A következő lépés indítása folyamatban…':statusName(run.status)):'Itt látod majd, mit végzett el.'}</h2></div>{run?.verifiedAt&&<ShieldCheck size={30}/>}</div>
     {!run?<div className="pw-result-empty"><FileText size={34}/><p>A feladat indítása után az egyes lépések és a kész anyag is itt jelenik meg.</p></div>:<>
      <p className="pw-run-name">{run.plan.name}{selectedChanged&&' · Fent már módosítottad a következő összeállítást.'}</p>
      <ol className="pw-progress">{actualSteps.map((id,i)=>{const done=run.events.some(e=>e.step===id&&e.status==='completed'),current=run.cursor===i;return <li key={id} data-state={done?'done':current?run.status:'later'}>{done?<Check size={17}/>:current&&run.status==='running'?<Loader2 className="pw-spin" size={17}/>:<span>{i+1}</span>}<span>{stepName(id)}</span></li>;})}</ol>
      <div className="pw-run-actions">{run.status==='draft'&&<Button disabled={busy||configured!==true} onClick={()=>void operate('start')}>Elindítom ezt az összeállítást</Button>}{run.status==='ready'&&!busy&&<Button disabled={configured!==true} onClick={()=>void operate('continue')}>Folytatom a következő lépéssel</Button>}{run.status==='waiting'&&<div className="pw-approval"><strong>A szöveg elkészült. Készítsen hozzá képet?</strong><p>Nézd át az anyagot. Az engedély egy képkészítési lépésre szól.</p><Button disabled={busy} onClick={()=>void operate('approve')}>Igen, készítsen képet</Button></div>}{run.status==='failed'&&<><p className="pw-error">{run.error}</p><Button disabled={busy} onClick={()=>void operate('retry')}><RotateCcw size={17}/> Csak a megállt lépést próbálja újra</Button><p className="pw-small">A korábbi kész lépések megmaradnak. Az ismételt AI-kérés új költséget okozhat.</p></>}{['running','ready','waiting','failed','draft'].includes(run.status)&&<Button variant="outline" onClick={()=>void stop()}><Pause size={16}/> Leállítom</Button>}</div>
      <div className="pw-tabs" role="group" aria-label="Munka nézete">{[['result','Kész anyag'],['steps','Mi történt?'],['sources','Források']].map(([id,label])=><button key={id} aria-pressed={tab===id} onClick={()=>setTab(id as typeof tab)}>{label}</button>)}</div>
      {tab==='result'&&(result?<div className="pw-text"><h3>{result.title}</h3><p>{result.summary}</p>{result.documents.map((d,i)=><article key={i}><h4>{d.title}</h4><div><LinkedText text={d.body}/></div></article>)}{result.questions.length>0&&<aside><strong>Ezt még pontosítsd a fenti kérésben:</strong><ul>{result.questions.map(q=><li key={q}>{q}</li>)}</ul><p>A válaszoddal új munkát indíthatsz.</p></aside>}{result.notes.length>0&&<aside><strong>Ezt nézd át:</strong><ul>{result.notes.map(n=><li key={n}>{n}</li>)}</ul></aside>}{image&&<img className="pw-image" src={image.url} alt="A szöveghez készített illusztráció"/>}</div>:<p>Még nincs kész szöveg. Az összeállítást a rendszer megőrizte.</p>)}
      {tab==='steps'&&<div className="pw-log"><p>A szerver által rögzített események. A mentés ellenőrzése a fájlok egyezését vizsgálja; a szöveg szakmai helyességét külön nézd át.</p>{run.events.map((e,i)=><div key={i}><time>{new Date(e.at).toLocaleTimeString('hu-HU')}</time><strong>{stepName(e.step)}</strong><span>{{saved:'Mentve',started:'Elindult',running:'Dolgozik',completed:'Elkészült',failed:'Megállt',waiting:'Jóváhagyásra vár',approved:'Engedélyezve',retry_requested:'Újrapróbálást kértél',cancelled:'Leállítva'}[e.status]||e.status}</span></div>)}<p>{run.attempts} elküldött AI-kérés; legfeljebb 10 egy feladatsorban. Jelentett tokenhasználat: {tokens.toLocaleString('hu-HU')}{unknown?' (részleges adat)':''}. Ez nem a szolgáltatói számla végösszege.</p>{run.outputs.length>1&&<details><summary>A korábbi lépések eredményei</summary>{run.outputs.map((o,i)=><article key={i}><h4>{stepName(o.step)}</h4>{o.result.documents.map((d,j)=><div key={j}><strong>{d.title}</strong><p className="pw-preserve">{d.body}</p></div>)}</article>)}</details>}</div>}
      {tab==='sources'&&(run.research?<ul className="pw-sources">{run.research.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} <ArrowRight size={16}/></a></li>)}</ul>:<p>{run.plan.steps.includes('search')?'Még nem készült el a forráskeresés.':'Ebben az összeállításban nem választottál internetes keresést.'}</p>)}
      {run.verifiedAt&&<div className="pw-receipt"><strong><ShieldCheck size={20}/> Mentés visszaellenőrizve</strong><p>A rendszer újra megnyitotta a mentett fájlokat, és összehasonlította őket az elkészült anyaggal.</p><div className="pw-files">{run.files.map(f=><a key={f.name} href={f.url} download={f.name}><Download size={18}/>{f.name}<small>{Math.ceil(f.bytes/1024)} kB</small></a>)}</div><div className="pw-folder"><Button variant="outline" onClick={()=>void chooseFolder()}><FolderOpen size={18}/>{folder?'Másik mappát választok':'Saját mappába is elteszem'}</Button>{folder&&<Button onClick={()=>void saveFolder()}>Mentés ide: {folder.name}</Button>}</div>{folderNotice&&<p role="status">{folderNotice}</p>}<details><summary>Mentési bizonylat</summary><p>Munka: {run.id}<br/>Ellenőrizve: {new Date(run.verifiedAt).toLocaleString('hu-HU')}</p>{run.files.map(f=><p key={f.name}>{f.name}<code>{f.sha256}</code></p>)}</details></div>}
      <div className="pw-bottom-actions"><Button variant="outline" disabled={busy} onClick={()=>{setPlan(run.plan);setRun(null);attempt.current=null;setNotice('Az összeállításból új munkát készíthetsz. A korábbi eredmény megmarad.');}}>Új munkaként használom</Button>{!busy&&run.status!=='running'&&(deleteAsk?<><span>Törlöd a mentett munkát és fájljait?</span><Button variant="outline" onClick={()=>void remove()}>Igen, törlöm</Button><button onClick={()=>setDeleteAsk(false)}>Mégsem</button></>:<button onClick={()=>setDeleteAsk(true)}><Trash2 size={16}/> Törlés</button>)}</div>
     </>}
    </section></section>
   <section id="pw-help" className="pw-help"><h2>Az első használat menete</h2><div><article><span>01</span><h3>Mondd el a célt.</h3><p>A kész szöveget az AI írja meg. Neked a témát és az elvárást kell megadnod.</p></article><article><span>02</span><h3>Válassz lépéseket.</h3><p>A + hozzáadja, az × kiveszi. Indítás előtt bármikor átállíthatod a sorrendet.</p></article><article><span>03</span><h3>Indítsd és nézd át.</h3><p>A képkészítés előtt engedélyt kér. Hibánál a már elkészült részek megmaradnak.</p></article><article><span>04</span><h3>Nyisd meg az eredményt.</h3><p>A munkatér megőrzi. Letöltheted, vagy támogató böngészőben kiválasztott mappába mentheted.</p></article></div><p>A próba felhős AI-t használ. A futtatás idejére hagyd nyitva az ablakot. Bezáráskor az aktuális lépés megszakadhat; visszatérve látod a mentett állapotot és folytathatod a munkát. Gmail- és Canva-csatlakoztatás, illetve időzített háttérmunka ebben a próbában még nincs.</p></section>
  </main><footer className="pw-footer"><Pawn size={20}/><span>Agent Akadémia</span><span>A privát próbád.</span></footer></div>;
}
