'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,Check,Download,FileText,Image as ImageIcon,Loader2,Search,ShieldCheck,X,FolderOpen} from 'lucide-react';
import {Pawn} from '../components/pawn';
import {Button} from '../components/ui/button';
import {Textarea} from '../components/ui/textarea';
import {Label} from '../components/ui/label';
import {workMarkdown,type AIResult,type WorkStep} from '../lib/ai-agent';
import {researchSteps} from '../lib/research-agent';
import {researchExample} from '../lib/research-example';
import './research-workshop.css';

type Work={id:string;brief:string;job:string;parentId:string|null;status:string;result:AIResult|null;steps?:WorkStep[];error:string|null;createdAt:string};
type API=State&{error?:string;work:Work};
type State={configured:boolean;profile:string;revision:number|null;works:Work[]};
function download(name:string,text:string,type='text/plain;charset=utf-8'){const url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const icons=[Search,FileText,ShieldCheck,ImageIcon,FolderOpen];
function LinkedText({text}:{text:string}){const parts=text.split(/(\[[^\]\n]{1,300}\]\(https?:\/\/[^\s)]+\))/g);return <>{parts.map((part,i)=>{const match=part.match(/^\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)$/);return match?<a key={i} href={match[2]} target="_blank" rel="noopener noreferrer">{match[1]}</a>:part;})}</>;}
export default function ResearchWorkshop({user=false,signInHref='/signin-with-chatgpt?return_to=%2Fproba'}:{user?:boolean;signInHref?:string}){
 const [available,setAvailable]=useState<boolean|null>(null),[prefsLoaded,setPrefsLoaded]=useState(false);
 const [state,setState]=useState<State|null>(null),[loading,setLoading]=useState(user),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const [topic,setTopic]=useState(''),[audience,setAudience]=useState('Teljesen kezdőknek, egyszerűen és barátságosan.'),[profile,setProfile]=useState(''),[work,setWork]=useState<Work|null>(null),[sample,setSample]=useState(false),[tab,setTab]=useState('text'),[busy,setBusy]=useState(false),[revision,setRevision]=useState('');
 const pending=useRef<{id:string;brief:string;parentId:string|null}|null>(null),working=useRef(false),resultRef=useRef<HTMLElement>(null);
 async function load(){setLoading(true);try{const r=await fetch('/api/ai?assistant=research',{cache:'no-store'}),s=await r.json() as API;if(!r.ok)throw Error(s.error||'A munkatér nem nyílt meg.');setState(s);setProfile(current=>current.trim()?current:s.profile);const active=s.works.find((w:Work)=>w.job==='kutato'&&w.status==='pending');if(active)await openWork(active.id);}catch(e){setError(e instanceof Error?e.message:'A munkatér nem nyílt meg.');}finally{setLoading(false);}}
 useEffect(()=>{if(!user)void fetch('/api/ai?capabilities=research',{cache:'no-store'}).then(async r=>{if(r.ok)setAvailable((await r.json() as {configured:boolean}).configured);}).catch(()=>{});},[user]);
 useEffect(()=>{try{const saved=localStorage.getItem('aa-research-audience');if(saved&&saved.length<=1000)setAudience(saved);}catch{}setPrefsLoaded(true);},[]);
 useEffect(()=>{if(prefsLoaded)try{localStorage.setItem('aa-research-audience',audience);}catch{}},[audience,prefsLoaded]);
 useEffect(()=>{if(user)void load();else{setState(null);setWork(null);setTopic('');setProfile('');pending.current=null;}},[user]);
 function accept(w:Work){setWork(w);setState(s=>s?{...s,works:[w,...s.works.filter(x=>x.id!==w.id)]}:s);}
 async function openWork(id:string){try{const r=await fetch('/api/ai?id='+id,{cache:'no-store'}),s=await r.json() as API;if(!r.ok)throw Error(s.error);setSample(false);accept(s.work);setTab('text');}catch(e){setError(e instanceof Error?e.message:'A mentett munka nem nyílt meg.');}}
 useEffect(()=>{if(work?.status!=='pending')return;let stopped=false;const id=work.id;const timer=setInterval(async()=>{try{const r=await fetch('/api/ai?id='+id,{cache:'no-store'});if(!r.ok){if(r.status===404&&!working.current&&!stopped){setWork(null);setNotice('A feladat nem indult el. A beírt szöveg megmaradt; a Készítsd el gombbal újrapróbálhatod.');}return;}const s=await r.json() as API;if(!stopped){accept(s.work);if(s.work.status!=='pending'){pending.current=null;setNotice(s.work.status==='succeeded'?'Elkészült. A munkateredben elmentettük.':'A munka megállt. Nézd meg, mi készült el.');}}}catch{/* The last confirmed state stays visible. */}},3500);return()=>{stopped=true;clearInterval(timer);};},[work?.id,work?.status]);
 async function start(followup=false){if(working.current||!state?.configured)return;const brief=followup?revision.trim():topic.trim()+'\nKinek és milyen stílusban: '+audience.trim();if((followup?revision:topic).trim().length<3)return;
  working.current=true;setBusy(true);setSample(false);setError('');setNotice('');setTab('text');
  const parentId=followup?work?.id||null:null;if(!pending.current||pending.current.brief!==brief||pending.current.parentId!==parentId)pending.current={id:crypto.randomUUID(),brief,parentId};
  const attempt=pending.current;
  try{
   if(profile!==state.profile){const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',content:profile,revision:state.revision})}),s=await r.json() as API;if(!r.ok)throw Error(s.error);setState(old=>old?{...old,profile:s.profile,revision:s.revision}:old);}
   const promise=fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'create',job:'kutato',...attempt})});
   // The local pending state claims no module completion; polls replace it with persisted events.
   setWork({id:attempt.id,brief,parentId,job:'kutato',status:'pending',result:null,steps:[],error:null,createdAt:new Date().toISOString()});
   const r=await promise,s=await r.json() as API;if(!r.ok){await openWork(attempt.id);throw Error(s.error||'Az indítás nem sikerült.');}accept(s.work);if(s.work.status!=='pending')pending.current=null;setRevision('');
  }catch(e){setError(e instanceof Error?e.message:'Megszakadt a kapcsolat.');setNotice('A korábbi munkák között ellenőrizheted, hogy elindult-e. Az azonos kérés újraküldése nem indít dupla munkát.');try{const r=await fetch('/api/ai?id='+attempt.id,{cache:'no-store'});if(r.ok){const s=await r.json() as API;accept(s.work);}else if(r.status===404)setWork(null);}catch{/* Preserve the unknown in-flight state. */}}
  finally{working.current=false;setBusy(false);}
 }
 const output=sample?researchExample:work?.result,running=busy||work?.status==='pending',steps=work?.steps||output?.steps||[],done=work?.status==='succeeded'&&!!(output?.image||output?.imageURL);
 const selected=sample?'Előre elkészített példa':running?'A segítőd dolgozik':done?'Elkészült és elmentve':work?.status==='failed'?'Itt állt meg a munka':output?.questions.length?'Egy pontosítás kell':'Itt jelenik meg az eredmény';
 const imageSrc=sample?'/examples/fuszernovenyek.webp':output?.imageURL?output.imageURL:output?.image?'data:'+output.image.mime+';base64,'+output.image.data:null;
 const exportText=()=>{if(!output)return;download(sample?'pelda-fuszernovenyek.md':'kesz-anyag.md',workMarkdown(output)+(output.research?'\n## Felhasznált források\n'+output.research.sources.map(s=>'- '+s.title+': '+s.url).join('\n'):'')+(sample?'\nElőre elkészített bemutató. Nem az oldalon most lefutott AI-munka.\n':''));};
 function showSample(){setSample(true);setTab('text');setTimeout(()=>resultRef.current?.focus(),0);}
 return <div className="rw"><header className="rw-header"><a href="/" className="rw-brand"><Pawn size={32}/><span>Agent Akadémia</span></a><a href="/"><ArrowLeft size={16}/> Vissza az építőhöz</a></header>
  <main className="rw-main"><div className="rw-heading"><p className="rw-eyebrow">PRÓBÁLJ KI EGY TELJES FELADATOT</p><h1>Egy témából kész anyag.</h1><p>Utánanéz, megírja, átnézi, képet készít hozzá, majd elmenti neked.</p></div>
   <div className="rw-grid"><section className="rw-input"><span className="rw-kicker">A TE RÉSZED</span><h2>Miről készüljön?</h2><Label htmlFor="rw-topic">Írd le a témát vagy a feladatot</Label><Textarea id="rw-topic" rows={4} value={topic} maxLength={4000} disabled={running} placeholder="Például: Fűszernövények nevelése egy kis erkélyen. Készíts belőle cikket és rövid posztot." onChange={e=>{setTopic(e.target.value);pending.current=null;}}/>
    <button className="rw-example-link" disabled={running} onClick={()=>setTopic('Készíts rövid, forrásokkal alátámasztott cikket és egy közösségi posztot arról, hogyan kezdjek fűszernövényeket nevelni egy kis erkélyen.')}>Ezt a feladatötletet választom</button>
    <details className="rw-settings"><summary>Kinek készüljön? <span>Megadhatod, ha fontos</span></summary><Label htmlFor="rw-audience">Olvasók és hangnem</Label><Textarea id="rw-audience" value={audience} maxLength={1000} rows={2} disabled={running} onChange={e=>setAudience(e.target.value)}/><Label htmlFor="rw-background">Amit rólad tudnia kell</Label><Textarea id="rw-background" value={profile} maxLength={12000} rows={3} disabled={running} onChange={e=>setProfile(e.target.value)} placeholder="Például: Kezdő hobbikertészeknek írok. Rövid, tegező szövegeket szeretek."/><p>Az indításkor megjegyzi a hátteredet a következő munkához is.</p></details>
    {!user&&available===false?<div className="rw-access"><strong>A saját feladat indítása még nem elérhető.</strong><p>Az AI-hozzáférést a működtetőnek kell bekapcsolnia. A kész példát addig is meg tudod nézni.</p></div>:!user?<div className="rw-access"><p>A saját feladatodhoz lépj be, hogy később is megtaláld az eredményt.</p><Button asChild><a href={signInHref} target="_top">Belépek és kipróbálom <ArrowRight size={18}/></a></Button></div>:loading?<p role="status">Megnyitjuk a munkateredet…</p>:state&&!state.configured?<div className="rw-access"><strong>A saját feladat indítása még nem elérhető.</strong><p>Az AI-hozzáférést a működtetőnek kell bekapcsolnia. Addig az elkészült példát meg tudod nézni.</p><Button variant="outline" onClick={()=>void load()}>Elérhetőség ellenőrzése</Button></div>:<Button className="rw-start" disabled={running||!state?.configured||topic.trim().length<3} onClick={()=>void start()}>{running?<><Loader2 className="rw-spin" size={18}/> Dolgozik…</>:<>Készítsd el <ArrowRight size={18}/></>}</Button>}
    <p className="rw-note">Az eredmény itt, a saját munkateredben jelenik meg. A feladatot és a hátteredet az AI-szolgáltató feldolgozza. Új munka indítása a működtető AI-keretét használja.</p>
    <button className="rw-sample-button" onClick={showSample}>Előbb megnézek egy kész példát <ArrowRight size={17}/></button>
    {state?.works.some(w=>w.job==='kutato')&&<details className="rw-history"><summary>Korábbi munkáim</summary>{state.works.filter(w=>w.job==='kutato').map(w=><button key={w.id} disabled={running} onClick={()=>void openWork(w.id)}>{w.result?.title||w.brief.slice(0,75)}<small>{w.status==='pending'?'Folyamatban':w.status==='failed'?'Megállt':'Megnyitás'}</small></button>)}</details>}
   </section>
   <section className="rw-result" ref={resultRef} tabIndex={-1}><div className="rw-result-heading"><span className="rw-kicker">A SEGÍTŐD RÉSZE</span><h2>{selected}</h2>{sample&&<p className="rw-sample-notice">Ez bemutatóanyag. A saját témáddal való indítás külön AI-munkát végez.{work&&<button className="rw-example-link" onClick={()=>setSample(false)}>Vissza a saját munkámhoz</button>}</p>}</div>
    <ol className="rw-steps">{researchSteps.map((s,i)=>{const step=steps.find(p=>p.id===s.id),status=sample?'example':s.id==='save'?(done?'completed':'waiting'):step?.status||(running&&i===0&&steps.length===0?'waiting':'waiting'),Icon=icons[i];return <li key={s.id} className={'rw-step rw-step-'+status}><span className="rw-step-icon">{status==='completed'?<Check size={18}/>:status==='running'?<Loader2 size={18} className="rw-spin"/>:status==='failed'?<X size={18}/>:<Icon size={18}/>}</span><span><strong>{s.name}</strong><small>{sample?s.detail:status==='completed'?'Elkészült':status==='running'?'Most ezen dolgozik':status==='failed'?'Nem fejeződött be':s.detail}</small></span></li>;})}</ol>
    {error&&<p role="alert" className="rw-error">{error}</p>}{work?.error&&!sample&&<p className="rw-error">{work.error}</p>}{notice&&<p role="status" className="rw-notice">{notice}</p>}
    {output?<div className="rw-output"><div className="rw-tabs" role="group" aria-label="Elkészült anyagok">{[['text','Szövegek'],['image','Kép'],['sources','Források']].map(([id,label])=><button key={id} id={'rw-tab-'+id} aria-pressed={tab===id} aria-controls="rw-panel" onClick={()=>setTab(id)}>{label}</button>)}</div><div id="rw-panel" role="region" aria-labelledby={'rw-tab-'+tab}>
     {tab==='text'&&<><h3>{output.title}</h3><p>{output.summary}</p>{output.documents.map((d,i)=><article key={i}><h4>{d.title}</h4><div className="rw-body"><LinkedText text={d.body}/></div></article>)}{output.notes.length>0&&<div className="rw-notice"><strong>Ezt nézd át használat előtt</strong><ul>{output.notes.map((n,i)=><li key={i}>{n}</li>)}</ul></div>}{output.questions.length>0&&<div className="rw-notice"><strong>Ezt még pontosítsd</strong><ul>{output.questions.map((q,i)=><li key={i}>{q}</li>)}</ul></div>}</>}
     {tab==='image'&&(imageSrc?<figure><img src={imageSrc} alt="A témához készített illusztráció"/><figcaption>{sample?'Előre elkészített példaillusztráció.':'Az AI a cikk témájából készítette. Letöltés előtt nézd át.'}</figcaption><a className="rw-download" href={imageSrc} download={sample?'pelda-illusztracio.webp':'illusztracio.jpg'}><Download size={17}/> Kép letöltése</a></figure>:<p>A kép még nem készült el. A szövegeket már megnyithatod.</p>)}
     {tab==='sources'&&(output.research?<><p>A keresés során kapott hivatkozások. A tartalmi állításokat a forrásoldalon is ellenőrizheted.</p><ul className="rw-sources">{output.research.sources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.title} <ArrowRight size={15}/></a></li>)}</ul><details><summary>Kutatási jegyzet</summary><div className="rw-body"><LinkedText text={output.research.text}/></div></details></>:<p>Még nincsenek megjeleníthető források.</p>)}
    </div>{output.documents.length>0&&<div className="rw-delivery"><Button variant="outline" onClick={exportText}><Download size={17}/> {sample?'Példaszöveg letöltése':'Szövegek letöltése'}</Button><p>{sample?'A letöltéssel a bemutató anyagát kapod.':'A böngésződ letöltései közé kerül. A mentett példány a Korábbi munkáim között marad.'}</p></div>}
    {!sample&&!running&&work?.status==='succeeded'&&<div className="rw-revision"><Label htmlFor="rw-revision">{output.questions.length?'Írd ide a válaszodat':'Mit változtasson rajta?'}</Label><Textarea id="rw-revision" rows={2} value={revision} maxLength={4000} onChange={e=>setRevision(e.target.value)} placeholder="Például: legyen rövidebb, és szóljon családoknak."/><Button disabled={!state?.configured||revision.trim().length<3} onClick={()=>void start(true)}>Új változat készítése</Button><p>A korábbi változat megmarad. Ez új keresést és új AI-munkát indít.</p></div>}</div>:<div className="rw-empty"><FileText size={40}/><h3>Egy cikk, egy poszt és egy kép.</h3><p>Mindet egy helyen kapod meg, a felhasznált forrásokkal együtt.</p><Button variant="outline" onClick={showSample}>Mutasd meg egy példán</Button></div>}
   </section></div>
   <footer className="rw-footer"><p>Egyelőre ezt az öt lépést tudod együtt kipróbálni. Az eredmény automatikusan nem kerül ki más oldalra.</p><a href="/">Vissza a saját összeállításhoz <ArrowRight size={16}/></a></footer>
  </main></div>;
}
