'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, Download, FolderOpen, Loader2, Trash2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { getTool } from '@/lib/daily-tools';
import { downloadFile } from './tool-workbench';
import type { SavedTool } from '@/lib/tool-save';
export default function ToolLibrary({user}:{user:boolean}){
 const [saves,setSaves]=useState<SavedTool[]>([]),[loading,setLoading]=useState(user),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[deleting,setDeleting]=useState<SavedTool|null>(null),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{if(!user)return;setLoading(true);try{const r=await fetch('/api/tools',{cache:'no-store'}),b=await r.json() as {error?:string;saves:SavedTool[]};if(!r.ok)throw new Error(b.error||'Nem sikerült a művelet.');setSaves(b.saves);setError('');}catch(e){setError(e instanceof Error?e.message:'A mentések nem tölthetők be.');}finally{setLoading(false);}},[user]);
 useEffect(()=>{void load();},[load]);
 const filtered=saves.filter(s=>(filter==='all'||s.kind===filter)&&(s.title+' '+getTool(s.toolId).name).toLocaleLowerCase('hu').includes(query.toLocaleLowerCase('hu')));
 return <section className="panel tool-library"><div className="section-heading"><div><div className="eyebrow">A SAJÁT MUNKÁID</div><h2>Mentett változatok és eredmények</h2><p>{user?`${saves.length} / 100 mentés a saját fiókodban.`:'A segédeket bejelentkezés nélkül is használhatod. A mentéshez lépj be.'}</p></div><Button asChild variant="outline"><Link href="/">Új segéd <ArrowRight/></Link></Button></div>
  {error&&<div className="error-callout" role="alert"><span>{error}</span><Button size="sm" variant="outline" onClick={()=>void load()}>Újrapróbálom</Button></div>}
  {loading?<p className="tool-loading"><Loader2 className="spin"/> Mentések betöltése…</p>:saves.length?<><div className="library-controls"><div className="category-tabs">{[['all','Összes'],['preset','Saját változat'],['result','Eredmény']].map(([id,label])=><Button key={id} variant={filter===id?'default':'ghost'} onClick={()=>setFilter(id)} aria-pressed={filter===id}>{label}</Button>)}</div><Input aria-label="Keresés a mentésekben" placeholder="Keresés a mentéseidben…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="saved-tool-list">{filtered.map(s=><article key={s.id}><span className="saved-tool-icon"><FolderOpen size={22}/></span><div><Link href={`/eszkozok/${s.toolId}?mentes=${s.id}`}><h3>{s.title}</h3></Link><p>{getTool(s.toolId).name} · {s.kind==='preset'?'Saját változat':'Mentett eredmény'} · {new Date(s.createdAt).toLocaleDateString('hu-HU')}</p></div><div className="saved-actions"><Button asChild size="sm" variant="outline"><Link href={`/eszkozok/${s.toolId}?mentes=${s.id}`}>Megnyitás <ArrowRight size={15}/></Link></Button><Button size="sm" variant="ghost" aria-label={s.title+' letöltése JSON-fájlként'} onClick={()=>downloadFile(s.toolId+'-mentes.json',JSON.stringify(s,null,2),'application/json')}><Download size={16}/></Button><Button size="sm" variant="ghost" aria-label={s.title+' törlése'} onClick={()=>setDeleting(s)}><Trash2 size={16}/></Button></div></article>)}</div>{!filtered.length&&<p className="field-note">Nincs ilyen mentés. Módosítsd a keresést vagy a szűrőt.</p>}</>:<div className="library-empty"><FolderOpen size={32}/><h3>Itt lesz helye az elvégzett munkának.</h3><p>Nyiss meg egy segédet, add meg az adataidat, majd mentsd el az eredményt vagy a saját változatodat.</p><Button asChild><Link href="/eszkozok/erdeklodo-rendezo">Kipróbálom az Érdeklődő-rendezőt <ArrowRight/></Link></Button></div>}
  <Dialog open={!!deleting} onOpenChange={v=>{if(!busy&&!v)setDeleting(null);}}><DialogContent><DialogHeader><DialogTitle>Törlöd ezt a mentést?</DialogTitle><DialogDescription>„{deleting?.title}” törlődik a munkaterületedről. A már letöltött fájljaid megmaradnak.</DialogDescription></DialogHeader><div className="button-row"><Button disabled={busy} variant="outline" onClick={()=>setDeleting(null)}>Mégsem</Button><Button disabled={busy} variant="destructive" onClick={async()=>{if(!deleting||busy)return;setBusy(true);try{const r=await fetch('/api/tools?id='+deleting.id,{method:'DELETE'}),b=await r.json() as {error?:string;saves:SavedTool[]};if(!r.ok)throw new Error(b.error||'Nem sikerült a művelet.');setSaves(s=>s.filter(x=>x.id!==deleting.id));setDeleting(null);setError('');}catch(e){setError(e instanceof Error?e.message:'Nem sikerült törölni.');setDeleting(null);}finally{setBusy(false);}}}>{busy?<Loader2 className="spin"/>:<Trash2/>} Mentés törlése</Button></div></DialogContent></Dialog>
 </section>;
}
