import { createHash } from 'node:crypto';
import type { getStore } from '@netlify/blobs';
import { AIError, validateAIInput, validateAIResult, type AIInput, type AIResult, type AIJob, type WorkStep } from '../../lib/ai-agent';
export type Store=ReturnType<typeof getStore>;
export type Work={steps?:WorkStep[];id:string;owner:string;parentId:string|null;job:AIJob;brief:string;input:AIInput;hash:string;status:'queued'|'pending'|'succeeded'|'failed';result:AIResult|null;error:string|null;createdAt:string;updatedAt:string};
type Admission={id:string;owner:string;at:number;active:boolean};
export const userKey=(id:string)=>createHash('sha256').update(id).digest('hex');
export const uuid=(id:unknown):id is string=>typeof id==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id);
export function visible(w:Work){const stale=(w.status==='pending'||w.status==='queued')&&Date.now()-Date.parse(w.createdAt)>480000;return {id:w.id,parentId:w.parentId,job:w.job,brief:w.brief,status:stale?'failed':w.status==='queued'?'pending':w.status,result:w.result,error:stale?'A futás megszakadt. Nem indul újra magától.':w.error,createdAt:w.createdAt,steps:w.steps||w.result?.steps||[]};}
export function key(owner:string,id:string){return owner+'/works/'+id;}
function condition(entry:{etag?:string}|null){if(entry){if(!entry.etag)throw new AIError('STORE','A mentés most nem zárolható.',503);return {onlyIfMatch:entry.etag};}return {onlyIfNew:true as const};}
async function edit<T>(store:Store,path:string,initial:T,change:(value:T)=>T){for(let i=0;i<6;i++){const previous=await store.getWithMetadata(path,{type:'json'});const value=change(previous?previous.data as T:initial);const done=await store.setJSON(path,value,condition(previous));if(done.modified)return value;}throw new AIError('CONFLICT','A munkatér elfoglalt. Próbáld újra.',409);}
async function reserve(store:Store,owner:string,id:string){await edit<Admission[]>(store,'usage',[],old=>{const now=Date.now(),entries=old.filter(x=>now-x.at<86400000);if(entries.some(x=>x.owner===owner&&x.id===id))throw new AIError('REPLAY','A kérés már rögzítve lett, de a munkája nem tölthető be. Nem indítunk dupla generálást.',409);if(entries.length>=200||entries.filter(x=>x.owner===owner).length>=20)throw new AIError('LIMIT','Elfogyott a napi keret. Egy fiók 24 óránként 20 kérést indíthat.',429);if(entries.some(x=>x.owner===owner&&x.active&&now-x.at<480000))throw new AIError('ACTIVE','Az agent már dolgozik. Várd meg az eredményét.',429);return [...entries,{id,owner,at:now,active:true}];});}
export async function release(store:Store,owner:string,id:string){await edit<Admission[]>(store,'usage',[],entries=>entries.map(x=>x.owner===owner&&x.id===id?{...x,active:false}:x));}
export async function readWorkspace(store:Store,owner:string){const profile=await store.get(owner+'/profile',{type:'json'}) as {content:string;revision:number}|null;const index=await store.get(owner+'/index',{type:'json'}) as string[]|null;const rows=await Promise.all((index||[]).slice(0,30).map(id=>store.get(key(owner,id),{type:'json'}) as Promise<Work|null>));return {profile:profile?.content||'',revision:profile?.revision??null,works:rows.filter((w):w is Work=>!!w&&w.owner===owner).map(w=>{const v=visible(w);return w.job==='kutato'&&v.result?{...v,result:{...v.result,image:undefined,research:undefined,documents:[]}}:v;})};}
export async function saveProfile(store:Store,owner:string,raw:unknown){const p=raw as {content?:unknown;revision?:unknown};if(typeof p.content!=='string'||p.content.length>12000||(p.revision!==null&&(!Number.isInteger(p.revision)||Number(p.revision)<1)))throw new AIError('INPUT','A háttér legfeljebb 12 000 karakter lehet.');const before=await store.getWithMetadata(owner+'/profile',{type:'json'});if((before?.data?.revision??null)!==p.revision)throw new AIError('CONFLICT','A háttér közben változott. Másold ki a saját szövegedet, majd töltsd újra az oldalt.',409);const next={content:p.content.trim(),revision:Number(p.revision??0)+1};const write=await store.setJSON(owner+'/profile',next,condition(before));if(!write.modified)throw new AIError('CONFLICT','A háttér másik ablakban változott. Töltsd újra az oldalt.',409);return {profile:next.content,revision:next.revision};}
export async function prepareWork(store:Store,owner:string,raw:unknown){
 const p=raw as Record<string,unknown>;if(!p||!uuid(p.id)||(p.parentId!==null&&!uuid(p.parentId))||typeof p.brief!=='string'||p.brief.trim().length<3||p.brief.length>6000)throw new AIError('INPUT','Írd le a feladatot, legfeljebb 6000 karakterben.');
 const request={id:p.id,parentId:p.parentId as string|null,job:p.job,brief:p.brief.trim()},hash=userKey(JSON.stringify(request));
 const existing=await store.get(key(owner,p.id),{type:'json'}) as Work|null;if(existing){if(existing.owner!==owner||existing.hash!==hash)throw new AIError('CONFLICT','Ehhez az azonosítóhoz más feladat tartozik.',409);return {work:existing,created:false};}
 let history:AIInput['history']=[];if(request.parentId){const parent=await store.get(key(owner,request.parentId),{type:'json'}) as Work|null;if(!parent||parent.owner!==owner||parent.status!=='succeeded'||!parent.result)throw new AIError('PARENT','Az előző munka nem található.',404);if(parent.job!==p.job)throw new AIError('PARENT','A folytatás az előző feladatfajtához tartozik.');history=[...parent.input.history,{brief:parent.brief,result:parent.result}];}
 const profile=await store.get(owner+'/profile',{type:'json'}) as {content:string}|null,input=validateAIInput({job:p.job,brief:p.brief,profile:profile?.content||'',history});
 await reserve(store,owner,p.id);
 const now=new Date().toISOString(),work:Work={id:p.id,owner,parentId:request.parentId,job:input.job,brief:input.brief,input,hash,status:'queued',result:null,error:null,createdAt:now,updatedAt:now};
 try{const saved=await store.setJSON(key(owner,p.id),work,{onlyIfNew:true});if(!saved.modified)throw new AIError('CONFLICT','A feladat már létezik. Frissítsd a munkát.',409);await edit<string[]>(store,owner+'/index',[],old=>[work.id,...old.filter(id=>id!==work.id)].slice(0,100));}catch(error){await failWork(store,owner,p.id,'A munka nem indult el: a mentése nem fejeződött be.').catch(()=>{});throw error;}
 return {work,created:true};
}
export async function failWork(store:Store,owner:string,id:string,message:string){const previous=await store.getWithMetadata(key(owner,id),{type:'json'});if(previous&&['queued','pending'].includes(previous.data.status))await store.setJSON(key(owner,id),{...previous.data,status:'failed',error:message,updatedAt:new Date().toISOString()},condition(previous));await release(store,owner,id);}
export async function runWork(store:Store,owner:string,id:string,generate:(input:AIInput,report:(steps:WorkStep[],partial:AIResult|null)=>Promise<void>)=>Promise<AIResult>){
 const previous=await store.getWithMetadata(key(owner,id),{type:'json'});if(!previous||previous.data.owner!==owner||previous.data.status!=='queued')return;
 if(Date.now()-Date.parse(previous.data.createdAt)>480000){await failWork(store,owner,id,'A sorba állított feladat lejárt. Indíts új munkát.');return;}
 const work:Work={...previous.data,status:'pending',updatedAt:new Date().toISOString()};const claim=await store.setJSON(key(owner,id),work,condition(previous));if(!claim.modified)return;
 const report=async(steps:WorkStep[],partial:AIResult|null)=>{await edit<Work>(store,key(owner,id),work,current=>{if(current.owner!==owner||current.status!=='pending')throw new AIError('STATE','A munka már lezárult.',409);return {...current,steps,result:partial?validateAIResult(partial):current.result,updatedAt:new Date().toISOString()};});};
 try{const result=validateAIResult(await generate(work.input,report));const latest=await store.getWithMetadata(key(owner,id),{type:'json'});if(!latest||latest.data.owner!==owner||latest.data.status!=='pending')throw new AIError('STATE','A munka már lezárult.',409);const saved=await store.setJSON(key(owner,id),{...latest.data,status:'succeeded',result,updatedAt:new Date().toISOString()},condition(latest));if(!saved.modified)throw new AIError('SAVE','A kész munka nem menthető.',503);}catch(e){await failWork(store,owner,id,e instanceof AIError?e.message:'A generálás megszakadt. A korábbi munkák megmaradtak.');return;}await release(store,owner,id);
}
