import React, {useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Pawn} from '../../components/pawn';
import AIStudio from '../../app/ai-studio';
import './local.css';
import '../../app/ai.css';
import '../../app/brand.css';
function LocalApp(){
 const [key,setKey]=useState(''),[configured,setConfigured]=useState<boolean|null>(null),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 useEffect(()=>{fetch('/api/setup').then(async r=>{const d=await r.json() as {error?:string;configured:boolean};if(!r.ok)throw new Error(d.error);setConfigured(d.configured);}).catch(()=>setError('A helyi program nem érhető el. Indítsd el újra az Indítás fájllal.'));},[]);
 async function connect(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/setup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setKey('');setConfigured(true);setMessage('A hozzáférés mentve. Most add meg az első feladatot; az ellenőrzi a generálás lehetőségét is.');setVersion(v=>v+1);}catch(e){setError(e instanceof Error?e.message:'A csatlakoztatás nem sikerült.');}finally{setBusy(false);}}
 async function importProfile(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;event.target.value='';setError('');if(file.size>24000){setError('Legfeljebb 12 000 karakteres szöveget tölts be.');return;}try{const text=await file.text();if(text.length>12000)throw new Error('A háttér legfeljebb 12 000 karakter lehet.');const previous=await fetch('/api/ai').then(r=>r.json() as Promise<{profile:string;revision:number|null}>);if(previous.profile&&!window.confirm('A betöltött szöveg lecseréli a korábbi hátteredet. Folytatod?'))return;const r=await fetch('/api/ai',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'profile',content:text,revision:previous.revision})}),d=await r.json() as {error?:string};if(!r.ok)throw new Error(d.error);setVersion(v=>v+1);setMessage('A háttér betöltve. Az agent a következő feladatnál már használja.');}catch(e){setError(e instanceof Error?e.message:'A fájl nem tölthető be.');}}
 return <><header className="local-header"><strong className="local-wordmark"><Pawn size={32}/><span>Agent <b className="brand-gold">Akadémia</b></span></strong><span>A saját gépeden</span></header><main className="local-main"><details className="local-setup" open={configured===false}><summary>{configured?'Csatlakoztatás és saját háttér':'Egyszeri beüzemelés · először ezt nyisd meg'}</summary><h2>Kapcsoljuk össze az agentet az AI-val.</h2><p>Ehhez OpenAI API-hozzáférés kell. A szolgáltató a használatért díjat számíthat fel. Az alábbi csatlakoztatás nem vásárol keretet, és még nem indít szöveggenerálást.</p><ol><li>Nyisd meg a <a href="https://platform.openai.com/api-keys" target="_blank" rel="noreferrer">saját OpenAI API-kulcsaidat</a>, és hozz létre kulcsot. A szolgáltatói fiókban állíts be használati keretet.</li><li>Másold ide a kulcsot. A helyi program ellenőrzi, és a saját gépeden menti el.</li><li>Zárd be ezt a részt, és add meg az első feladatot.</li></ol><form onSubmit={e=>void connect(e)}><label htmlFor="local-key">OpenAI API-kulcs</label><input id="local-key" type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} required minLength={15} maxLength={400}/><button disabled={busy}>{busy?'Kapcsolat ellenőrzése…':configured?'Hozzáférés cseréje':'Csatlakoztatom'}</button></form><p className="local-note">A kulcs a helyi program privát beállításfájljába kerül. A csomag továbbadásakor csak az eredeti ZIP-et oszd meg.</p><label className="local-file">Már megírtad a hátteredet? Töltsd be szövegfájlból.<input type="file" accept=".txt,.md,text/plain,text/markdown" onChange={e=>void importProfile(e)}/></label></details>{error&&<p className="simple-error" role="alert">{error}</p>}{message&&<p className="ai-notice" role="status">{message}</p>}<AIStudio key={version} user local/></main></>;
}
createRoot(document.getElementById('root')!).render(<LocalApp/>);
